Repository Hous-Release/hous-AOS, pull requests merged in 2022-11, with the labels that each got.

#100 #99 [ui, fix] 프로필 뷰 내에 오각형 구현
  app/src/main/java/hous/release/android/presentation/badge/BadgeActivity.kt
  app/src/main/java/hous/release/android/presentation/badge/HousBadgeScreen.kt
  app/src/main/java/hous/release/android/presentation/personality/result/PersonalityResultActivity.kt
  app/src/main/java/hous/release/android/presentation/profile/ProfileFragment.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/daily/DailyFragment.kt
  app/src/main/java/hous/release/android/presentation/todo/main/TodoFragment.kt
  app/src/main/java/hous/release/android/util/component/DailyTap.kt
  app/src/main/java/hous/release/android/util/component/HomieMessageFrame.kt
  app/src/main/java/hous/release/android/util/component/HousBadge.kt
  app/src/main/java/hous/release/android/util/component/MemberTap.kt
  app/src/main/java/hous/release/android/util/component/Pentagon.kt
  app/src/main/java/hous/release/android/util/component/PersonalityResultImage.kt
  app/src/main/java/hous/release/android/util/component/ToDoProgressBar.kt
  app/src/main/java/hous/release/android/util/component/TodoMainEmpty.kt
  app/src/main/java/hous/release/android/util/style/Theme.kt
  app/src/main/java/hous/release/android/util/style/Type.kt
  app/src/main/res/layout/activity_personality_result.xml
  app/src/main/res/layout/fragment_profile.xml
  domain/src/main/java/hous/release/domain/entity/TestScore.kt
Labels: 원용🐉, ui, fix, Pull Request🔥

#103 #97 [ui] 설정, 알림 설정 레이아웃
  app/src/main/AndroidManifest.xml
  app/src/main/java/hous/release/android/presentation/settings/NotificationSettingsActivity.kt
  app/src/main/java/hous/release/android/presentation/settings/SettingsActivity.kt
  app/src/main/res/drawable/ic_alarm.xml
  app/src/main/res/drawable/ic_feedback.xml
  app/src/main/res/drawable/ic_info.xml
  app/src/main/res/drawable/ic_radio_checked.xml
  app/src/main/res/drawable/ic_radio_unchecked.xml
  app/src/main/res/drawable/ic_settings_next.xml
  app/src/main/res/drawable/selector_radio_button.xml
  app/src/main/res/drawable/selector_switch_thumb.xml
  app/src/main/res/drawable/selector_switch_track.xml
  app/src/main/res/layout/activity_notification_settings.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/values/strings.xml
Labels: 연주😻, ui, Pull Request🔥

#102 #96 [ui, feat] todo 추가 뷰, 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/hous/release/android/presentation/todo/add/AddToDoFragment.kt
  app/src/main/java/hous/release/android/presentation/todo/add/AddToDoVIewModel.kt
  app/src/main/java/hous/release/android/presentation/todo/add/AddTodoUserScreen.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/daily/DailyFragment.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/member/MemberFragment.kt
  app/src/main/java/hous/release/android/presentation/todo/viewmodel/UpdateToDoViewModel.kt
  app/src/main/java/hous/release/android/util/binding/BindingAdapters.kt
  app/src/main/java/hous/release/android/util/component/DayItems.kt
  app/src/main/java/hous/release/android/util/component/ToDoButton.kt
  app/src/main/java/hous/release/android/util/component/ToDoUserItem.kt
  app/src/main/java/hous/release/android/util/component/ToDoUserProfile.kt
  app/src/main/java/hous/release/android/util/component/ToDoUserScreen.kt
  app/src/main/java/hous/release/android/util/extension/HomyTypeExtension.kt
  app/src/main/java/hous/release/android/util/extension/LifecycleExtension.kt
  app/src/main/java/hous/release/android/util/style/Theme.kt
  app/src/main/res/drawable/ic_alarm_off.xml
  app/src/main/res/drawable/ic_alarm_on.xml
  app/src/main/res/drawable/selector_push_notification.xml
  app/src/main/res/layout/fragment_add_to_do.xml
  app/src/main/res/navigation/nav_todo_detail.xml
  app/src/main/res/values/strings.xml
  domain/src/main/java/hous/release/domain/entity/response/ToDoUser.kt
Labels: 준원🐻, feat, ui, Pull Request🔥

#108 #107 [feat] todo 추가 서버 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/hous/release/android/HousMessageService.kt
  app/src/main/java/hous/release/android/di/RepositoryModule.kt
  app/src/main/java/hous/release/android/presentation/login/LoginViewModel.kt
  app/src/main/java/hous/release/android/presentation/todo/add/AddToDoVIewModel.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/TodoDetailActivity.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/TodoDetailViewModel.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/daily/DailyFragment.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/member/MemberFragment.kt
  data/build.gradle.kts
  data/src/main/java/hous/release/data/datasource/TodoDataSource.kt
  data/src/main/java/hous/release/data/entity/request/UpdateToDoUsersRequest.kt
  data/src/main/java/hous/release/data/entity/response/ToDoUsersResponse.kt
  data/src/main/java/hous/release/data/repository/AuthRepositoryImpl.kt
  data/src/main/java/hous/release/data/repository/TodoRepositoryImpl.kt
  data/src/main/java/hous/release/data/service/BadgeService.kt
  data/src/main/java/hous/release/data/service/TodoService.kt
  domain/src/main/java/hous/release/domain/entity/UpdateToDoUser.kt
  domain/src/main/java/hous/release/domain/entity/response/ToDoUser.kt
  domain/src/main/java/hous/release/domain/repository/AuthRepository.kt
  domain/src/main/java/hous/release/domain/repository/TodoRepository.kt
  domain/src/main/java/hous/release/domain/usecase/GetToDoUsersUseCase.kt
  domain/src/main/java/hous/release/domain/usecase/PostAddToDoUseCase.kt
Labels: 준원🐻, feat, Pull Request🔥

#114 #95 [ui, feat] ProfileEdit 뷰, 서버 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/hous/release/android/presentation/login/UserInputActivity.kt
  app/src/main/java/hous/release/android/presentation/login/UserInputViewModel.kt
  app/src/main/java/hous/release/android/presentation/personality/result/PersonalityResultActivity.kt
  app/src/main/java/hous/release/android/presentation/profile/ProfileFragment.kt
  app/src/main/java/hous/release/android/presentation/profile/ProfileViewModel.kt
  app/src/main/java/hous/release/android/presentation/profile/edit/ProfileEditActivity.kt
  app/src/main/java/hous/release/android/presentation/profile/edit/ProfileEditViewModel.kt
  app/src/main/java/hous/release/android/presentation/profile/edit/ProfileEntity.kt
  app/src/main/java/hous/release/android/util/binding/BindingAdapters.kt
  app/src/main/java/hous/release/android/util/dialog/DatePickerClickListener.kt
  app/src/main/java/hous/release/android/util/dialog/DatePickerDialog.kt
  app/src/main/res/color/selector_profile_edit_text.xml
  app/src/main/res/drawable/ic_profile_edit_checked.xml
  app/src/main/res/drawable/ic_profile_edit_unchecked.xml
  app/src/main/res/drawable/selector_profile_edit.xml
  app/src/main/res/drawable/selector_profile_edit_check.xml
  app/src/main/res/drawable/shape_blue_i2_fill_8_rect.xml
  app/src/main/res/drawable/shape_blue_i2_fill_bottom8_rect.xml
  app/src/main/res/drawable/shape_blue_i2_fill_top8_rect.xml
  app/src/main/res/drawable/shape_blue_line_rect.xml
  app/src/main/res/drawable/shape_g3_line_rect.xml
  app/src/main/res/layout/activity_personality_result.xml
  app/src/main/res/layout/activity_profile_edit.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/values/appearance.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/hous/release/data/datasource/ProfileDataSource.kt
  data/src/main/java/hous/release/data/entity/request/ProfileEditRequest.kt
  data/src/main/java/hous/release/data/entity/response/ProfileResponse.kt
  data/src/main/java/hous/release/data/repository/ProfileRepositoryImpl.kt
  data/src/main/java/hous/release/data/service/ProfileService.kt
  domain/src/main/java/hous/release/domain/entity/response/Profile.kt
  domain/src/main/java/hous/release/domain/repository/ProfileRepository.kt
  domain/src/main/java/hous/release/domain/usecase/GetProfileUseCase.kt
  domain/src/main/java/hous/release/domain/usecase/PutProfileEditUseCase.kt
Labels: 영주🐼, feat, ui, Pull Request🔥

#116 #115 [ui] 성향 테스트 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/hous/release/android/presentation/personality/PersonalityActivity.kt
  app/src/main/java/hous/release/android/presentation/personality/test/PersonalityTestFragment.kt
  app/src/main/java/hous/release/android/presentation/personality/test/PersonalityTestStartFragment.kt
  app/src/main/java/hous/release/android/presentation/profile/ProfileFragment.kt
  app/src/main/res/color/selector_personality_test_text.xml
  app/src/main/res/drawable/ic_test_left.xml
  app/src/main/res/drawable/ic_test_profile.xml
  app/src/main/res/drawable/ic_test_right.xml
  app/src/main/res/drawable/selector_personality_test_btn.xml
  app/src/main/res/drawable/shape_blue_fill_8_rect.xml
  app/src/main/res/drawable/shape_red_b_1_fill_8_rect.xml
  app/src/main/res/layout/activity_personality.xml
  app/src/main/res/layout/fragment_personality_test.xml
  app/src/main/res/layout/fragment_personality_test_start.xml
  app/src/main/res/layout/item_personality_test.xml
  app/src/main/res/layout/item_personality_test_loading.xml
  app/src/main/res/navigation/nav_personality.xml
  app/src/main/res/values/strings.xml
Labels: 원용🐉, ui, Pull Request🔥

#124 #104 [ui] 방 퇴사하기, 회원탈퇴하기
  app/src/main/AndroidManifest.xml
  app/src/main/java/hous/release/android/presentation/out_room/OutRoomActivity.kt
  app/src/main/java/hous/release/android/presentation/withdraw/WithdrawActivity.kt
  app/src/main/res/drawable/ic_bg_out_room_bottom.xml
  app/src/main/res/drawable/ic_out_room_graphic.xml
  app/src/main/res/drawable/ic_withdraw_checked.xml
  app/src/main/res/drawable/ic_withdraw_feedback_down.xml
  app/src/main/res/drawable/ic_withdraw_unchecked.xml
  app/src/main/res/drawable/selector_withdraw_check.xml
  app/src/main/res/drawable/shape_red_fill_20_rect.xml
  app/src/main/res/layout/activity_out_room.xml
  app/src/main/res/layout/activity_withdraw.xml
  app/src/main/res/layout/item_out_room_my_to_do.xml
  app/src/main/res/values/strings.xml
Labels: 연주😻, ui, Pull Request🔥

#127 #117 [feat] 성향 테스트 기능 구현
  app/src/main/java/hous/release/android/presentation/personality/PersonalityActivity.kt
  app/src/main/java/hous/release/android/presentation/personality/result/PersonalityResultActivity.kt
  app/src/main/java/hous/release/android/presentation/personality/result/PersonalityResultViewModel.kt
  app/src/main/java/hous/release/android/presentation/personality/test/PersonalityTestAdapter.kt
  app/src/main/java/hous/release/android/presentation/personality/test/PersonalityTestFragment.kt
  app/src/main/java/hous/release/android/presentation/personality/test/PersonalityTestViewModel.kt
  app/src/main/java/hous/release/android/presentation/profile/ProfileViewModel.kt
  app/src/main/res/drawable/ic_test_left_click.xml
  app/src/main/res/drawable/ic_test_right_click.xml
  app/src/main/res/drawable/selector_test_left_direction.xml
  app/src/main/res/drawable/selector_test_right_direction.xml
  app/src/main/res/layout/fragment_personality_test.xml
  app/src/main/res/layout/item_personality_test.xml
  app/src/main/res/layout/item_personality_test_loading.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/hous/release/data/datasource/PersonalityDataSource.kt
  data/src/main/java/hous/release/data/entity/PersonalityTestEntity.kt
  data/src/main/java/hous/release/data/entity/response/ColorEntity.kt
  data/src/main/java/hous/release/data/repository/PersonalityRepositoryImpl.kt
  data/src/main/java/hous/release/data/service/PersonalityService.kt
  domain/src/main/java/hous/release/domain/entity/PersonalityTest.kt
  domain/src/main/java/hous/release/domain/repository/PersonalityRepository.kt
  domain/src/main/java/hous/release/domain/usecase/GetPersonalityTestsUseCase.kt
  domain/src/main/java/hous/release/domain/usecase/PutPersonalityTestResult.kt
Labels: 원용🐉, feat, Pull Request🔥

#126 #122 [fix] 레포지토리 대신 유즈케이스로 변경, 성향테스트 컬러값 로직 구현
  app/src/main/java/hous/release/android/presentation/login/LoginViewModel.kt
  app/src/main/java/hous/release/android/presentation/login/UserInputActivity.kt
  app/src/main/java/hous/release/android/presentation/personality/result/PersonalityResultActivity.kt
  app/src/main/java/hous/release/android/presentation/personality/result/PersonalityResultViewModel.kt
  app/src/main/java/hous/release/android/presentation/profile/ProfileFragment.kt
  app/src/main/java/hous/release/android/presentation/profile/edit/ProfileEditActivity.kt
  app/src/main/java/hous/release/android/util/dialog/DatePickerClickListener.kt
  app/src/main/java/hous/release/android/util/dialog/DatePickerDialog.kt
  app/src/main/res/layout/fragment_profile.xml
  domain/src/main/java/hous/release/domain/usecase/GetFcmTokenUseCase.kt
  domain/src/main/java/hous/release/domain/usecase/GetPersonalityResultUseCase.kt
  domain/src/main/java/hous/release/domain/usecase/InitTokenUseCase.kt
  domain/src/main/java/hous/release/domain/usecase/PostLoginUseCase.kt
  domain/src/main/java/hous/release/domain/usecase/PostSignUpUseCase.kt
Labels: 영주🐼, feat, fix, Pull Request🔥

#119 #118 [fix] main 규칙 ui, 기능 수정
  app/src/main/java/hous/release/android/presentation/our_rules/main_rule/OurRulesViewModel.kt
  app/src/main/res/layout/item_our_rules_representative_rule_bottom.xml
  app/src/main/res/layout/item_our_rules_representative_rule_middle.xml
  domain/src/main/java/hous/release/domain/entity/response/OurRule.kt
Labels: 준원🐻, fix

#125 #121 [ui/feat] 호미프로필 ui/api 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/hous/release/android/presentation/hous/HousFragment.kt
  app/src/main/java/hous/release/android/presentation/hous/HousViewModel.kt
  app/src/main/java/hous/release/android/presentation/hous/adapter/HomiesAdapter.kt
  app/src/main/java/hous/release/android/presentation/login/LoginViewModel.kt
  app/src/main/java/hous/release/android/presentation/profile/ProfileFragment.kt
  app/src/main/java/hous/release/android/presentation/profile/edit/ProfileEditViewModel.kt
  app/src/main/java/hous/release/android/presentation/profile/homie/HomieProfileActivity.kt
  app/src/main/java/hous/release/android/presentation/profile/homie/HomieProfileViewModel.kt
  app/src/main/java/hous/release/android/util/binding/BindingAdapters.kt
  app/src/main/res/drawable/ic_homie_profile_blue.xml
  app/src/main/res/drawable/ic_homie_profile_green.xml
  app/src/main/res/drawable/ic_homie_profile_purple.xml
  app/src/main/res/drawable/ic_homie_profile_red.xml
  app/src/main/res/drawable/ic_homie_profile_yellow.xml
  app/src/main/res/drawable/shape_g3_fill_52_circle.xml
  app/src/main/res/layout/activity_homie_profile.xml
  app/src/main/res/layout/activity_personality_result.xml
  app/src/main/res/layout/activity_user_input.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/item_hous_homies.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/hous/release/data/datasource/ProfileDataSource.kt
  data/src/main/java/hous/release/data/repository/ProfileRepositoryImpl.kt
  data/src/main/java/hous/release/data/service/ProfileService.kt
  domain/src/main/java/hous/release/domain/repository/ProfileRepository.kt
  domain/src/main/java/hous/release/domain/usecase/GetHomieProfileUseCase.kt
Labels: 영주🐼, feat, ui, Pull Request🔥

#130 #120 [feat, ui] 규칙 수정 기능, 서버 수정
  app/src/main/java/hous/release/android/presentation/our_rules/adapter/OurRulesAddAdapter.kt
  app/src/main/java/hous/release/android/presentation/our_rules/adapter/OurRulesEditAdapter.kt
  app/src/main/java/hous/release/android/presentation/our_rules/add_rule/OurRuleAddFragment.kt
  app/src/main/java/hous/release/android/presentation/our_rules/edit_rule/OurRuleEditFragment.kt
  app/src/main/java/hous/release/android/presentation/our_rules/edit_rule/OurRuleEditViewModel.kt
  app/src/main/res/layout/item_our_rules_edit_item.xml
  app/src/main/res/values/colors.xml
  data/src/main/java/hous/release/data/datasource/OurRulesDataSource.kt
  data/src/main/java/hous/release/data/entity/request/EditRulesRequest.kt
  data/src/main/java/hous/release/data/repository/OurRulesRepositoryImpl.kt
  domain/src/main/java/hous/release/domain/repository/OurRulesRepository.kt
  domain/src/main/java/hous/release/domain/usecase/PutEditOurRulesUseCase.kt
Labels: 준원🐻, feat, ui, Pull Request🔥

#129 #105 [feat] 방 퇴사하기, 회원탈퇴하기, 로그인/회원가입 시 Hous 토큰 저장
  app/src/main/AndroidManifest.xml
  app/src/main/java/hous/release/android/di/RepositoryModule.kt
  app/src/main/java/hous/release/android/di/RetrofitModule.kt
  app/src/main/java/hous/release/android/di/RetrofitServiceModule.kt
  app/src/main/java/hous/release/android/di/SharedPrefModule.kt
  app/src/main/java/hous/release/android/presentation/login/LoginViewModel.kt
  app/src/main/java/hous/release/android/presentation/login/UserInputViewModel.kt
  app/src/main/java/hous/release/android/presentation/out_room/OutRoomActivity.kt
  app/src/main/java/hous/release/android/presentation/out_room/OutRoomViewModel.kt
  app/src/main/java/hous/release/android/presentation/out_room/adapter/MyToDoAdapter.kt
  app/src/main/java/hous/release/android/presentation/settings/SettingsActivity.kt
  app/src/main/java/hous/release/android/presentation/withdraw/WithdrawActivity.kt
  app/src/main/java/hous/release/android/presentation/withdraw/WithdrawViewModel.kt
  app/src/main/res/drawable/selector_withdraw_spinner.xml
  app/src/main/res/layout/activity_out_room.xml
  app/src/main/res/layout/activity_withdraw.xml
  app/src/main/res/layout/item_out_room_my_to_do.xml
  app/src/main/res/layout/item_withdraw_feedback.xml
  app/src/main/res/layout/item_withdraw_feedback_title.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/withdraw_feedback_items.xml
  data/src/main/java/hous/release/data/datasource/AuthDataSource.kt
  data/src/main/java/hous/release/data/datasource/LocalPrefTokenDataSource.kt
  data/src/main/java/hous/release/data/datasource/SettingsDataSource.kt
  data/src/main/java/hous/release/data/entity/request/DeleteUserRequest.kt
  data/src/main/java/hous/release/data/entity/response/SettingsMyToDoResponse.kt
  data/src/main/java/hous/release/data/repository/AuthRepositoryImpl.kt
  data/src/main/java/hous/release/data/repository/SettingsRepositoryImpl.kt
  data/src/main/java/hous/release/data/service/AuthService.kt
  data/src/main/java/hous/release/data/service/SettingsService.kt
  domain/src/main/java/hous/release/domain/entity/FeedbackType.kt
  domain/src/main/java/hous/release/domain/entity/response/SettingsMyToDo.kt
  domain/src/main/java/hous/release/domain/repository/AuthRepository.kt
  domain/src/main/java/hous/release/domain/repository/SettingsRepository.kt
  domain/src/main/java/hous/release/domain/usecase/InitHousTokenUseCase.kt
  domain/src/main/java/hous/release/domain/usecase/InitTokenUseCase.kt
Labels: 연주😻, feat, Pull Request🔥

#136 #134 [ui][feat] 디자인 나온 것 적용 및 방 참여 16명 초과 시 토스트 띄우기
  app/src/main/assets/welcome_blue_wednesday.json
  app/src/main/assets/welcome_green_friday.json
  app/src/main/assets/welcome_purple_thursday.json
  app/src/main/assets/welcome_red_tuesday.json
  app/src/main/assets/welcome_yellow_monday.json
  app/src/main/java/hous/release/android/presentation/enter_room/EnterRoomFragment.kt
  app/src/main/java/hous/release/android/presentation/enter_room/create_room/CreateRoomDialogFragment.kt
  app/src/main/java/hous/release/android/presentation/enter_room/create_room/CreateRoomFragment.kt
  app/src/main/java/hous/release/android/presentation/enter_room/enter_room_code/EnterRoomCodeDialogFragment.kt
  app/src/main/java/hous/release/android/presentation/enter_room/enter_room_code/EnterRoomCodeFragment.kt
  app/src/main/java/hous/release/android/presentation/enter_room/enter_room_code/EnterRoomCodeViewModel.kt
  app/src/main/java/hous/release/android/presentation/hous/adapter/HomiesAdapter.kt
  app/src/main/java/hous/release/android/presentation/notification/NotificationActivity.kt
  app/src/main/java/hous/release/android/presentation/notification/NotificationViewModel.kt
  app/src/main/java/hous/release/android/util/binding/BindingAdapters.kt
  app/src/main/res/animator/anim_enter_room_button.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/ic_profile_gray.xml
  app/src/main/res/drawable/ic_withdraw_graphic.xml
  app/src/main/res/layout/activity_notification.xml
  app/src/main/res/layout/activity_withdraw.xml
  app/src/main/res/layout/dialog_create_room.xml
  app/src/main/res/layout/dialog_enter_room_code.xml
  app/src/main/res/layout/fragment_hous.xml
  app/src/main/res/layout/item_hous_homies.xml
  app/src/main/res/values/strings.xml
Labels: 연주😻, feat, ui, Pull Request🔥

#137 #101 [feat] splash 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/assets/splash.json
  app/src/main/java/hous/release/android/presentation/enter_room/create_room/CreateRoomViewModel.kt
  app/src/main/java/hous/release/android/presentation/enter_room/enter_room_code/EnterRoomCodeViewModel.kt
  app/src/main/java/hous/release/android/presentation/login/UserInputViewModel.kt
  app/src/main/java/hous/release/android/presentation/out_room/OutRoomViewModel.kt
  app/src/main/java/hous/release/android/presentation/splash/IntroActivity.kt
  app/src/main/java/hous/release/android/presentation/tutorial/TutorialViewModel.kt
  app/src/main/res/layout/activity_intro.xml
  data/src/main/java/hous/release/data/datasource/EnterRoomDataSource.kt
  data/src/main/java/hous/release/data/datasource/LocalPrefSkipTutorialDataSource.kt
  data/src/main/java/hous/release/data/datasource/LocalSplashDataSource.kt
  data/src/main/java/hous/release/data/entity/response/GetRoomDetailResponse.kt
  data/src/main/java/hous/release/data/repository/AuthRepositoryImpl.kt
  data/src/main/java/hous/release/data/repository/EnterRoomRepositoryImpl.kt
  data/src/main/java/hous/release/data/service/EnterRoomService.kt
  domain/src/main/java/hous/release/domain/entity/SplashState.kt
  domain/src/main/java/hous/release/domain/entity/response/RoomDetail.kt
  domain/src/main/java/hous/release/domain/repository/AuthRepository.kt
  domain/src/main/java/hous/release/domain/repository/EnterRoomRepository.kt
  domain/src/main/java/hous/release/domain/usecase/GetEnterRoomInfoUseCase.kt
  domain/src/main/java/hous/release/domain/usecase/GetIsAccessTokenUseCase.kt
  domain/src/main/java/hous/release/domain/usecase/GetSplashStateUseCase.kt
  domain/src/main/java/hous/release/domain/usecase/SetSplashStateUseCase.kt
Labels: 원용🐉, feat, Pull Request🔥

#132 #123 [ui/fix] Profile 로티 붙이기, 대표배지 empty
  app/src/main/assets/profile_blue_no.json
  app/src/main/assets/profile_blue_yes.json
  app/src/main/assets/profile_gray.json
  app/src/main/assets/profile_green_no.json
  app/src/main/assets/profile_green_yes.json
  app/src/main/assets/profile_purple_no.json
  app/src/main/assets/profile_purple_yes.json
  app/src/main/assets/profile_red_no.json
  app/src/main/assets/profile_red_yes.json
  app/src/main/assets/profile_yellow_no.json
  app/src/main/assets/profile_yellow_yes.json
  app/src/main/java/hous/release/android/presentation/profile/ProfileFragment.kt
  app/src/main/java/hous/release/android/presentation/profile/homie/HomieProfileActivity.kt
  app/src/main/java/hous/release/android/util/binding/BindingAdapters.kt
  app/src/main/res/drawable/ic_homie_profile_nobadge.xml
  app/src/main/res/layout/activity_homie_profile.xml
  app/src/main/res/layout/activity_profile_edit.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  domain/src/main/java/hous/release/domain/entity/ProfileSet.kt
Labels: 영주🐼, ui, fix, Pull Request🔥

#139 #131 [feat] 강제로그인 구현
  app/src/main/java/hous/release/android/presentation/login/LoginActivity.kt
  app/src/main/java/hous/release/android/presentation/login/LoginViewModel.kt
  app/src/main/java/hous/release/android/util/binding/BindingAdapters.kt
  data/src/main/java/hous/release/data/datasource/AuthDataSource.kt
  data/src/main/java/hous/release/data/repository/AuthRepositoryImpl.kt
  data/src/main/java/hous/release/data/service/AuthService.kt
  domain/src/main/java/hous/release/domain/repository/AuthRepository.kt
  domain/src/main/java/hous/release/domain/usecase/PostForceLoginUseCase.kt
Labels: 영주🐼, feat, Pull Request🔥

#142 #141 [ui/feat] 401 토큰 만료 처리 및 디자인 수정 사항 적용
  app/src/main/AndroidManifest.xml
  app/src/main/assets/welcome_blue_wednesday.json
  app/src/main/assets/welcome_green_friday.json
  app/src/main/assets/welcome_purple_thursday.json
  app/src/main/assets/welcome_red_tuesday.json
  app/src/main/assets/welcome_weekend.json
  app/src/main/assets/welcome_yellow_monday.json
  app/src/main/ic_app_logo-playstore.png
  app/src/main/java/hous/release/android/HousMessageService.kt
  app/src/main/java/hous/release/android/di/RefreshRetrofitModule.kt
  app/src/main/java/hous/release/android/di/RepositoryModule.kt
  app/src/main/java/hous/release/android/di/RetrofitModule.kt
  app/src/main/java/hous/release/android/di/RetrofitServiceModule.kt
  app/src/main/java/hous/release/android/presentation/login/LoginActivity.kt
  app/src/main/java/hous/release/android/presentation/login/LoginViewModel.kt
  app/src/main/java/hous/release/android/presentation/out_room/OutRoomActivity.kt
  app/src/main/java/hous/release/android/presentation/profile/ProfileFragment.kt
  app/src/main/java/hous/release/android/presentation/profile/edit/ProfileEditViewModel.kt
  app/src/main/java/hous/release/android/presentation/settings/SettingsActivity.kt
  app/src/main/java/hous/release/android/presentation/withdraw/WithdrawActivity.kt
  app/src/main/java/hous/release/android/util/binding/BindingAdapters.kt
  app/src/main/res/drawable/ic_app_logo_background.xml
  app/src/main/res/drawable/ic_hous.xml
  app/src/main/res/layout/activity_out_room.xml
  app/src/main/res/layout/fragment_hous.xml
  app/src/main/res/layout/item_withdraw_feedback_title.xml
  app/src/main/res/mipmap-anydpi-v26/ic_app_logo.xml
  app/src/main/res/mipmap-anydpi-v26/ic_app_logo_round.xml
  app/src/main/res/mipmap-hdpi/ic_app_logo.png
  app/src/main/res/mipmap-hdpi/ic_app_logo_foreground.png
  app/src/main/res/mipmap-hdpi/ic_app_logo_round.png
  app/src/main/res/mipmap-mdpi/ic_app_logo.png
  app/src/main/res/mipmap-mdpi/ic_app_logo_foreground.png
  app/src/main/res/mipmap-mdpi/ic_app_logo_round.png
  app/src/main/res/mipmap-xhdpi/ic_app_logo.png
  app/src/main/res/mipmap-xhdpi/ic_app_logo_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_app_logo_round.png
  app/src/main/res/mipmap-xxhdpi/ic_app_logo.png
  app/src/main/res/mipmap-xxhdpi/ic_app_logo_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_app_logo_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_app_logo.png
  app/src/main/res/mipmap-xxxhdpi/ic_app_logo_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_app_logo_round.png
  app/src/main/res/values/strings.xml
  data/src/main/java/hous/release/data/datasource/RefreshDataSource.kt
  data/src/main/java/hous/release/data/entity/response/HousResponse.kt
  data/src/main/java/hous/release/data/entity/response/RefreshHousTokenResponse.kt
  data/src/main/java/hous/release/data/repository/RefreshRepositoryImpl.kt
  data/src/main/java/hous/release/data/service/RefreshService.kt
  domain/src/main/java/hous/release/domain/entity/response/RefreshHousToken.kt
  domain/src/main/java/hous/release/domain/repository/RefreshRepository.kt
Labels: 연주😻, feat, ui, Pull Request🔥

#144 #138 [feat/fix] firebase analytics 추가, 성향테스트 수정
  app/build.gradle.kts
  app/src/main/assets/loading.json
  app/src/main/assets/test_result.json
  app/src/main/java/hous/release/android/HousApplication.kt
  app/src/main/java/hous/release/android/HousMessageService.kt
  app/src/main/java/hous/release/android/presentation/personality/test/PersonalityTestFragment.kt
  app/src/main/java/hous/release/android/presentation/personality/test/PersonalityTestViewModel.kt
  app/src/main/java/hous/release/android/util/component/Pentagon.kt
  app/src/main/res/layout/item_personality_test_loading.xml
  buildSrc/src/main/java/Deps.kt
  data/src/main/java/hous/release/data/repository/AuthRepositoryImpl.kt
  domain/src/main/java/hous/release/domain/repository/AuthRepository.kt
  domain/src/main/java/hous/release/domain/usecase/GetFcmTokenUseCase.kt
Labels: 원용🐉, feat, fix, Pull Request🔥

#146 #145 [feat] 로그인 시 SplashState 초기화 해주기
  app/src/main/java/hous/release/android/di/RefreshRetrofitModule.kt
  app/src/main/java/hous/release/android/di/RetrofitModule.kt
  app/src/main/java/hous/release/android/presentation/login/LoginViewModel.kt
  data/src/main/java/hous/release/data/datasource/LocalPrefTokenDataSource.kt
Labels: 연주😻, feat, Pull Request🔥

#143 #135 [feat] 로딩 뷰 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/hous/release/android/presentation/our_rules/add_rule/OurRuleAddFragment.kt
  app/src/main/java/hous/release/android/presentation/our_rules/delete_rule/OurRuleDeleteFragment.kt
  app/src/main/java/hous/release/android/presentation/our_rules/edit_rule/OurRuleEditFragment.kt
  app/src/main/java/hous/release/android/presentation/todo/add/AddToDoFragment.kt
  app/src/main/java/hous/release/android/presentation/todo/add/AddTodoUserScreen.kt
  app/src/main/java/hous/release/android/presentation/todo/edit/EditToDoFragment.kt
  app/src/main/java/hous/release/android/presentation/todo/edit/EditToDoUserScreen.kt
  app/src/main/java/hous/release/android/util/component/ToDoButton.kt
  app/src/main/java/hous/release/android/util/component/ToDoUserScreen.kt
  app/src/main/java/hous/release/android/util/dialog/LoadingDialogFragment.kt
  app/src/main/java/hous/release/android/util/dialog/WarningDialogFragment.kt
  app/src/main/res/layout/dialog_loading.xml
  app/src/main/res/layout/fragment_our_rule_add.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 준원🐻, feat, ui

#148 #140 [ui] Profile 타이틀 텍스트 설정
  app/src/main/java/hous/release/android/presentation/login/LoginViewModel.kt
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/values/strings.xml
Labels: 영주🐼, ui, Pull Request🔥

#150 #149 [fix] HomieProfile putExtra 설정
  app/src/main/java/hous/release/android/presentation/profile/homie/HomieProfileActivity.kt
Labels: 영주🐼, hotfix🚨, Pull Request🔥
