Repository Hous-Release/hous-AOS, pull requests merged in 2022-10, with the labels that each got.

#42 #40 [feat] Hous 화면 서버 연결
  app/src/main/java/hous/release/android/di/RepositoryModule.kt
  app/src/main/java/hous/release/android/di/RetrofitServiceModule.kt
  app/src/main/java/hous/release/android/presentation/enter_room/create_room/CreateRoomViewModel.kt
  app/src/main/java/hous/release/android/presentation/enter_room/enter_room_code/EnterRoomCodeViewModel.kt
  app/src/main/java/hous/release/android/presentation/hous/HousFragment.kt
  app/src/main/java/hous/release/android/presentation/hous/HousViewModel.kt
  app/src/main/java/hous/release/android/presentation/hous/adapter/HomiesAdapter.kt
  app/src/main/res/drawable/ic_profile_gray.xml
  app/src/main/res/drawable/selector_enter_room.xml
  app/src/main/res/drawable/selector_enter_room_code.xml
  app/src/main/res/drawable/shape_g5_fill_10_rect.xml
  app/src/main/res/layout/fragment_hous.xml
  app/src/main/res/layout/item_hous_homies.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/hous/release/data/datasource/HousDataSource.kt
  data/src/main/java/hous/release/data/entity/response/HousResponse.kt
  data/src/main/java/hous/release/data/repository/EnterRoomRepositoryImpl.kt
  data/src/main/java/hous/release/data/repository/HousRepositoryImpl.kt
  data/src/main/java/hous/release/data/service/HousService.kt
  domain/src/main/java/hous/release/domain/MyClass.kt
  domain/src/main/java/hous/release/domain/entity/HomyType.kt
  domain/src/main/java/hous/release/domain/entity/response/Hous.kt
  domain/src/main/java/hous/release/domain/repository/HousRepository.kt
Labels: 연주😻, feat, Pull Request🔥

#44 #38 [feat] todo 삭제하기 기능 구현
  .idea/inspectionProfiles/Project_Default.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/hous/release/android/presentation/todo/daily/DailyActivity.kt
  app/src/main/java/hous/release/android/presentation/todo/daily/DailyAdapter.kt
  app/src/main/java/hous/release/android/presentation/todo/daily/DailyMyTodoAdapter.kt
  app/src/main/java/hous/release/android/presentation/todo/daily/DailyViewModel.kt
  app/src/main/java/hous/release/android/presentation/todo/main/TodoFragment.kt
  app/src/main/java/hous/release/android/presentation/todo/main/TodoViewModel.kt
  app/src/main/java/hous/release/android/util/TodoBottomSheet.kt
  app/src/main/java/hous/release/android/util/TodoDeleteDialog.kt
  app/src/main/res/drawable/inset_shape_white_fill_8_rect.xml
  app/src/main/res/drawable/shape_blue_fill_12_circle.xml
  app/src/main/res/drawable/shape_g_1_fill_6_rect.xml
  app/src/main/res/drawable/shape_green_fill_12_circle.xml
  app/src/main/res/drawable/shape_purple_fill_12_circle.xml
  app/src/main/res/drawable/shape_red_fill_12_circle.xml
  app/src/main/res/drawable/shape_yellow_fill_12_circle.xml
  app/src/main/res/layout/activity_daily.xml
  app/src/main/res/layout/dialog_to_do_bottom_sheet.xml
  app/src/main/res/layout/dialog_to_do_delete.xml
  app/src/main/res/layout/item_to_do_participant.xml
  app/src/main/res/navigation/nav_main.xml
  app/src/main/res/navigation/nav_todo.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/hous/release/data/datasource/TodoDataSource.kt
  data/src/main/java/hous/release/data/entity/response/TodoDetailResponse.kt
  data/src/main/java/hous/release/data/repository/TodoRepositoryImpl.kt
  data/src/main/java/hous/release/data/service/TodoService.kt
  domain/src/main/java/hous/release/domain/entity/TodoDetail.kt
  domain/src/main/java/hous/release/domain/repository/TodoRepository.kt
  domain/src/main/java/hous/release/domain/usecase/DeleteTodoUseCase.kt
  domain/src/main/java/hous/release/domain/usecase/GetTodoDetailUseCase.kt
Labels: 원용🐉, feat, ui, Pull Request🔥

#45 #35 [ui] Tutorial Activity 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/hous/release/android/presentation/login/LoginActivity.kt
  app/src/main/java/hous/release/android/presentation/login/UserInputActivity.kt
  app/src/main/java/hous/release/android/presentation/login/UserInputViewModel.kt
  app/src/main/java/hous/release/android/presentation/tutorial/TutorialActivity.kt
  app/src/main/java/hous/release/android/presentation/tutorial/TutorialViewModel.kt
  app/src/main/java/hous/release/android/presentation/tutorial/adapter/TutorialAdapter.kt
  app/src/main/res/drawable/ic_user_input_check_not.xml
  app/src/main/res/drawable/selector_tutorial_index.xml
  app/src/main/res/drawable/selector_user_input_check_birthday.xml
  app/src/main/res/drawable/shape_blue_fill_16_rect.xml
  app/src/main/res/drawable/shape_blue_fill_circle.xml
  app/src/main/res/drawable/shape_g3_fill_circle.xml
  app/src/main/res/drawable/shape_g4_fill_16_rect.xml
  app/src/main/res/layout/activity_tutorial.xml
  app/src/main/res/layout/activity_user_input.xml
  app/src/main/res/layout/item_tutorial.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
  data/src/main/java/hous/release/data/datasource/TutorialDataSource.kt
  domain/src/main/java/hous/release/domain/entity/TutorialEntity.kt
Labels: 영주🐼, feat, ui, Pull Request🔥

#49 #47 [feat, ui] 멤버별 보기 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/hous/release/android/presentation/todo/daily/DailyActivity.kt
  app/src/main/java/hous/release/android/presentation/todo/daily/DailyAdapter.kt
  app/src/main/java/hous/release/android/presentation/todo/daily/DailyMyTodoAdapter.kt
  app/src/main/java/hous/release/android/presentation/todo/daily/DailyOurTodoAdapter.kt
  app/src/main/java/hous/release/android/presentation/todo/main/MyTodoAdapter.kt
  app/src/main/java/hous/release/android/presentation/todo/main/OurTodoAdapter.kt
  app/src/main/java/hous/release/android/presentation/todo/member/MemberActivity.kt
  app/src/main/java/hous/release/android/presentation/todo/member/MemberAdapter.kt
  app/src/main/java/hous/release/android/presentation/todo/member/MemberTap.kt
  app/src/main/java/hous/release/android/presentation/todo/member/MemberTodoAdapter.kt
  app/src/main/java/hous/release/android/presentation/todo/member/MemberViewModel.kt
  app/src/main/java/hous/release/android/util/TodoBottomSheet.kt
  app/src/main/java/hous/release/android/util/TodoParticipantAdapter.kt
  app/src/main/res/drawable/ic_checked.xml
  app/src/main/res/drawable/ic_to_do_down.xml
  app/src/main/res/drawable/ic_to_do_up.xml
  app/src/main/res/drawable/shape_g_1_fill_8_rect.xml
  app/src/main/res/drawable/shape_g_5_fill_12_circle.xml
  app/src/main/res/layout/activity_member.xml
  app/src/main/res/layout/item_to_do_daily.xml
  app/src/main/res/layout/item_to_do_daily_my_rule.xml
  app/src/main/res/layout/item_to_do_member.xml
  app/src/main/res/layout/item_to_do_member_day_of_week.xml
  app/src/main/res/layout/item_to_do_participant.xml
  data/src/main/java/hous/release/data/datasource/TodoDataSource.kt
  data/src/main/java/hous/release/data/entity/response/MemberTodoResponse.kt
  data/src/main/java/hous/release/data/entity/response/TodoDetailResponse.kt
  data/src/main/java/hous/release/data/repository/TodoRepositoryImpl.kt
  data/src/main/java/hous/release/data/service/TodoService.kt
  domain/src/main/java/hous/release/domain/entity/MemberTodo.kt
  domain/src/main/java/hous/release/domain/entity/TodoDetail.kt
  domain/src/main/java/hous/release/domain/entity/response/MemberTodoContent.kt
  domain/src/main/java/hous/release/domain/repository/TodoRepository.kt
  domain/src/main/java/hous/release/domain/usecase/GetMemberTodosUseCase.kt
Labels: 원용🐉, feat, ui, Pull Request🔥

#34 #5 [ui] UserInput 뷰 구현 + Tutorial 뷰 수정
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  app/src/main/java/hous/release/android/di/RepositoryModule.kt
  app/src/main/java/hous/release/android/di/SharedPrefModule.kt
  app/src/main/java/hous/release/android/presentation/login/LoginActivity.kt
  app/src/main/java/hous/release/android/presentation/login/UserInputActivity.kt
  app/src/main/java/hous/release/android/presentation/login/UserInputViewModel.kt
  app/src/main/java/hous/release/android/presentation/tutorial/TutorialActivity.kt
  app/src/main/java/hous/release/android/presentation/tutorial/TutorialViewModel.kt
  app/src/main/java/hous/release/android/presentation/tutorial/adapter/TutorialAdapter.kt
  app/src/main/java/hous/release/android/util/extension/ContextExt.kt
  app/src/main/res/drawable/ic_inserinput_unchecked.xml
  app/src/main/res/drawable/ic_userinput_checked.xml
  app/src/main/res/drawable/selector_user_input_check_birthday.xml
  app/src/main/res/drawable/selector_userinput_button.xml
  app/src/main/res/drawable/selector_userinput_check.xml
  app/src/main/res/layout/activity_user_input.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/hous/release/data/datasource/LocalPrefSkipTutorialDataSource.kt
  data/src/main/java/hous/release/data/datasource/TutorialDataSource.kt
  data/src/main/java/hous/release/data/repository/AuthRepositoryImpl.kt
  domain/src/main/java/hous/release/domain/repository/AuthRepository.kt
  domain/src/main/java/hous/release/domain/usecase/InitSkipTutorialUseCase.kt
Labels: 영주🐼, ui, Pull Request🔥

#51 #41 [feat] 규칙 추가하기 + 뒤로가기 2번할 때 종료
  .idea/codeStyles/Project.xml
  .idea/ktlint.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/hous/release/android/di/DispatcherModule.kt
  app/src/main/java/hous/release/android/di/RepositoryModule.kt
  app/src/main/java/hous/release/android/di/RetrofitModule.kt
  app/src/main/java/hous/release/android/presentation/login/LoginActivity.kt
  app/src/main/java/hous/release/android/presentation/main/MainActivity.kt
  app/src/main/java/hous/release/android/presentation/our_rules/OurRulesFragment.kt
  app/src/main/java/hous/release/android/presentation/our_rules/OurRulesNavigateBottomSheet.kt
  app/src/main/java/hous/release/android/presentation/our_rules/OurRulesViewModel.kt
  app/src/main/java/hous/release/android/presentation/our_rules/adapter/OurRulesAddAdapter.kt
  app/src/main/java/hous/release/android/presentation/our_rules/add_rule/OurRuleAddErrorDialogFragment.kt
  app/src/main/java/hous/release/android/presentation/our_rules/add_rule/OurRuleAddFragment.kt
  app/src/main/java/hous/release/android/presentation/our_rules/add_rule/OurRuleAddOutDialogFragment.kt
  app/src/main/java/hous/release/android/presentation/our_rules/add_rule/OurRuleAddViewModel.kt
  app/src/main/java/hous/release/android/presentation/our_rules/type/SaveButtonState.kt
  app/src/main/java/hous/release/android/presentation/tutorial/TutorialActivity.kt
  app/src/main/java/hous/release/android/util/binding/BindingFragment.kt
  app/src/main/java/hous/release/android/util/extension/DialogFragmentExtension.kt
  app/src/main/res/drawable/ic_hous.xml
  app/src/main/res/layout/dialog_our_rule_add_error.xml
  app/src/main/res/layout/dialog_our_rule_add_out.xml
  app/src/main/res/layout/fragment_our_rule_add.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/hous/release/data/datasource/OurRulesDataSource.kt
  data/src/main/java/hous/release/data/entity/request/AddRulesRequest.kt
  data/src/main/java/hous/release/data/repository/OurRulesRepositoryImpl.kt
  data/src/main/java/hous/release/data/service/OurRulesService.kt
  domain/src/main/java/hous/release/domain/entity/ApiResult.kt
  domain/src/main/java/hous/release/domain/entity/OurRulesContent.kt
  domain/src/main/java/hous/release/domain/repository/OurRulesRepository.kt
  domain/src/main/java/hous/release/domain/usecase/GetOurMainRulesUseCase.kt
  domain/src/main/java/hous/release/domain/usecase/GetOurRulesUseCase.kt
  domain/src/main/java/hous/release/domain/usecase/OurRulesUseCase.kt
  domain/src/main/java/hous/release/domain/usecase/PostAddRulesUseCase.kt
Labels: 준원🐻, feat, Pull Request🔥

#56 #55 [ui] 규칙 수정 UI 구현
  .idea/codeStyles/Project.xml
  app/src/main/java/hous/release/android/presentation/our_rules/delete_rule/OurRuleDeleteFragment.kt
  app/src/main/java/hous/release/android/presentation/our_rules/edit_rule/OurRuleEditFragment.kt
  app/src/main/java/hous/release/android/presentation/our_rules/edit_rule/OurRuleEditViewModel.kt
  app/src/main/java/hous/release/android/presentation/our_rules/main_rule/OurRulesFragment.kt
  app/src/main/java/hous/release/android/presentation/our_rules/main_rule/OurRulesNavigateBottomSheet.kt
  app/src/main/java/hous/release/android/presentation/our_rules/main_rule/OurRulesViewModel.kt
  app/src/main/res/layout/fragment_our_rule.xml
  app/src/main/res/layout/fragment_our_rule_add.xml
  app/src/main/res/layout/fragment_our_rule_delete.xml
  app/src/main/res/layout/fragment_our_rule_edit.xml
  app/src/main/res/layout/item_our_rules_general_rule.xml
  app/src/main/res/layout/item_our_rules_representative_rule_bottom.xml
  app/src/main/res/layout/item_our_rules_representative_rule_middle.xml
  app/src/main/res/layout/item_our_rules_representative_rule_top.xml
  app/src/main/res/navigation/nav_our_rules.xml
  app/src/main/res/values/strings.xml
Labels: 준원🐻, ui, Pull Request🔥

#67 #57 [ui, feat] 방 이름 수정하기 및 WarningDailogUtil 제작
  .idea/codeStyles/Project.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/hous/release/android/presentation/enter_room/create_room/CreateRoomFragment.kt
  app/src/main/java/hous/release/android/presentation/enter_room/enter_room_code/EnterRoomCodeFragment.kt
  app/src/main/java/hous/release/android/presentation/hous/EditHousNameActivity.kt
  app/src/main/java/hous/release/android/presentation/hous/HousFragment.kt
  app/src/main/java/hous/release/android/util/dialog/ConfirmClickListener.kt
  app/src/main/java/hous/release/android/util/dialog/WarningDialogContent.kt
  app/src/main/java/hous/release/android/util/dialog/WarningDialogFragment.kt
  app/src/main/java/hous/release/android/util/dialog/WarningType.kt
  app/src/main/res/layout/activity_edit_hous_name.xml
  app/src/main/res/layout/dialog_warning.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 연주😻, feat, ui, Pull Request🔥

#63 #53 [ui, feat] to do 개수 초과시 다이얼로그 구현
  app/src/main/java/hous/release/android/presentation/todo/detail/TodoBottomSheet.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/TodoDeleteDialog.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/TodoDetailActivity.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/TodoDetailViewModel.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/TodoLimitDialog.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/daily/DailyFragment.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/member/MemberFragment.kt
  app/src/main/res/layout/activity_todo_detail.xml
  app/src/main/res/layout/dialog_todo_limit.xml
  app/src/main/res/layout/fragment_daily.xml
  app/src/main/res/layout/fragment_member.xml
  app/src/main/res/values/strings.xml
Labels: 원용🐉, feat, ui, Pull Request🔥

#61 #48 Login api 에러별 분기처리
  .idea/codeStyles/Project.xml
  app/src/main/java/hous/release/android/presentation/login/LoginActivity.kt
  app/src/main/java/hous/release/android/presentation/login/LoginViewModel.kt
  app/src/main/res/layout/activity_tutorial.xml
  app/src/main/res/layout/item_tutorial.xml
  app/src/main/res/values/appearance.xml
  data/src/main/java/hous/release/data/datasource/AuthDataSource.kt
  data/src/main/java/hous/release/data/entity/TokenEntity.kt
  data/src/main/java/hous/release/data/entity/response/LoginResponse.kt
  data/src/main/java/hous/release/data/repository/AuthRepositoryImpl.kt
  domain/src/main/java/hous/release/domain/entity/Token.kt
  domain/src/main/java/hous/release/domain/entity/response/Login.kt
  domain/src/main/java/hous/release/domain/repository/AuthRepository.kt
Labels: 영주🐼, feat, fix, Pull Request🔥

#72 #58 [feat] 방 이름 수정하기 서버 연결
  app/src/main/java/hous/release/android/presentation/enter_room/create_room/CreateRoomFragment.kt
  app/src/main/java/hous/release/android/presentation/enter_room/create_room/CreateRoomViewModel.kt
  app/src/main/java/hous/release/android/presentation/enter_room/enter_room_code/EnterRoomCodeFragment.kt
  app/src/main/java/hous/release/android/presentation/enter_room/enter_room_code/EnterRoomCodeViewModel.kt
  app/src/main/java/hous/release/android/presentation/hous/EditHousNameActivity.kt
  app/src/main/java/hous/release/android/presentation/hous/EditHousNameViewModel.kt
  app/src/main/java/hous/release/android/presentation/hous/HousFragment.kt
  app/src/main/java/hous/release/android/util/KeyBoardUtil.kt
  app/src/main/res/layout/activity_edit_hous_name.xml
  app/src/main/res/layout/dialog_warning.xml
  app/src/main/res/layout/fragment_create_room.xml
  app/src/main/res/layout/fragment_enter_room_code.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  data/src/main/java/hous/release/data/datasource/EnterRoomDataSource.kt
  data/src/main/java/hous/release/data/datasource/HousDataSource.kt
  data/src/main/java/hous/release/data/entity/request/EditHousNameRequest.kt
  data/src/main/java/hous/release/data/repository/EnterRoomRepositoryImpl.kt
  data/src/main/java/hous/release/data/repository/HousRepositoryImpl.kt
  data/src/main/java/hous/release/data/service/EnterRoomService.kt
  data/src/main/java/hous/release/data/service/HousService.kt
  domain/src/main/java/hous/release/domain/entity/request/DomainCreateRoomRequest.kt
  domain/src/main/java/hous/release/domain/entity/response/DomainEnterRoomResponse.kt
  domain/src/main/java/hous/release/domain/entity/response/NewRoom.kt
  domain/src/main/java/hous/release/domain/entity/response/Room.kt
  domain/src/main/java/hous/release/domain/repository/EnterRoomRepository.kt
  domain/src/main/java/hous/release/domain/repository/HousRepository.kt
Labels: 연주😻, feat

#70 #69 [ui, feat] todo 호미 이미지 추가
  app/src/main/java/hous/release/android/presentation/todo/main/ToDoProgressBar.kt
  app/src/main/java/hous/release/android/util/HomieMessageFrame.kt
  app/src/main/res/drawable/ic_to_do_temp_homie.xml
  app/src/main/res/drawable/ic_todo_homies_progress.xml
Labels: 원용🐉, feat, ui, Pull Request🔥

#66 #62 [feat] UserInput api 붙이기
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/hous/release/android/di/RepositoryModule.kt
  app/src/main/java/hous/release/android/di/SharedPrefModule.kt
  app/src/main/java/hous/release/android/presentation/login/LoginViewModel.kt
  app/src/main/java/hous/release/android/presentation/login/UserInputActivity.kt
  app/src/main/java/hous/release/android/presentation/login/UserInputViewModel.kt
  app/src/main/res/drawable/ic_userinput_unchecked.xml
  app/src/main/res/drawable/selector_userinput_check.xml
  app/src/main/res/layout/activity_user_input.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/java/Deps.kt
  data/src/main/java/hous/release/data/datasource/AuthDataSource.kt
  data/src/main/java/hous/release/data/datasource/LocalPrefSkipTutorialDataSource.kt
  data/src/main/java/hous/release/data/datasource/LocalPrefTokenDataSource.kt
  data/src/main/java/hous/release/data/entity/request/SignUpRequest.kt
  data/src/main/java/hous/release/data/entity/response/SignUpResponse.kt
  data/src/main/java/hous/release/data/repository/AuthRepositoryImpl.kt
  data/src/main/java/hous/release/data/service/AuthService.kt
  domain/src/main/java/hous/release/domain/entity/response/SignUp.kt
  domain/src/main/java/hous/release/domain/repository/AuthRepository.kt
  domain/src/main/java/hous/release/domain/usecase/PostSignUpUseCase.kt
Labels: 영주🐼, feat, Pull Request🔥

#68 #65 [feat, ui] 하우스 오각형 구현
  app/src/main/java/hous/release/android/presentation/todo/detail/daily/DailyFragment.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/member/MemberFragment.kt
  app/src/main/java/hous/release/android/util/HousFloatingButton.kt
  app/src/main/java/hous/release/android/util/component/DailyTap.kt
  app/src/main/java/hous/release/android/util/component/HomieMessageFrame.kt
  app/src/main/java/hous/release/android/util/component/HousFloatingButton.kt
  app/src/main/java/hous/release/android/util/component/MemberTap.kt
  app/src/main/java/hous/release/android/util/component/Pentagon.kt
  app/src/main/java/hous/release/android/util/component/RoundedLinearIndicator.kt
  app/src/main/java/hous/release/android/util/component/ToDoProgressBar.kt
  app/src/main/res/drawable/ic_todo_plus.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/colors.xml
Labels: 원용🐉, feat, ui, Pull Request🔥

#75 #73 Tutorial 이미지 삽입
  app/src/main/java/hous/release/android/presentation/login/LoginViewModel.kt
  app/src/main/java/hous/release/android/presentation/tutorial/TutorialActivity.kt
  app/src/main/java/hous/release/android/presentation/tutorial/adapter/TutorialAdapter.kt
  app/src/main/res/drawable/ic_tutorial_1.xml
  app/src/main/res/drawable/ic_tutorial_2.xml
  app/src/main/res/drawable/ic_tutorial_3.xml
  app/src/main/res/drawable/ic_tutorial_4.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/item_tutorial.xml
  domain/src/main/java/hous/release/domain/entity/TutorialEntity.kt
  domain/src/main/java/hous/release/domain/repository/AuthRepository.kt
Labels: 영주🐼, ui, Pull Request🔥

#79 #21 [feat] 방 참여코드 공유하기
  app/src/main/AndroidManifest.xml
  app/src/main/java/hous/release/android/presentation/enter_room/create_room/CreateRoomDialogFragment.kt
  app/src/main/java/hous/release/android/presentation/hous/HousFragment.kt
  app/src/main/res/drawable/ic_create_room_graphic.xml
  app/src/main/res/drawable/ic_create_room_start_graphic.xml
  app/src/main/res/drawable/ic_enter_room_graphic.xml
  app/src/main/res/drawable/ic_enter_room_start_graphic.xml
  app/src/main/res/layout/dialog_create_room.xml
  app/src/main/res/layout/dialog_enter_room_code.xml
  app/src/main/res/layout/fragment_enter_room.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/hous/release/data/entity/response/HousResponse.kt
  domain/src/main/java/hous/release/domain/entity/response/Hous.kt
Labels: 연주😻, feat, ui, Pull Request🔥

#80 #64 [ui] 배지 뷰 구현
  app/build.gradle.kts
  app/src/main/java/hous/release/android/presentation/badge/HousBadgeScreen.kt
  app/src/main/java/hous/release/android/presentation/enter_room/enter_room_code/EnterRoomCodeViewModel.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/TodoBottomSheet.kt
  app/src/main/java/hous/release/android/util/component/HousBadge.kt
  app/src/main/java/hous/release/android/util/component/ToDoProgressBar.kt
  app/src/main/res/drawable/ic_badge_check.xml
  app/src/main/res/drawable/ic_badge_lock.xml
  app/src/main/res/drawable/ic_badge_star.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/java/Deps.kt
  domain/src/main/java/hous/release/domain/entity/Badge.kt
Labels: 원용🐉, ui, Pull Request🔥

#77 #60 [feat] 우리집 규칙 수정 기능 구현 + empty 뷰/기능 구현
  .idea/codeStyles/Project.xml
  app/src/main/java/hous/release/android/presentation/hous/HousFragment.kt
  app/src/main/java/hous/release/android/presentation/our_rules/adapter/OurRulesAdapter.kt
  app/src/main/java/hous/release/android/presentation/our_rules/adapter/OurRulesEditAdapter.kt
  app/src/main/java/hous/release/android/presentation/our_rules/add_rule/OurRuleAddErrorDialogFragment.kt
  app/src/main/java/hous/release/android/presentation/our_rules/add_rule/OurRuleAddFragment.kt
  app/src/main/java/hous/release/android/presentation/our_rules/add_rule/OurRuleAddOutDialogFragment.kt
  app/src/main/java/hous/release/android/presentation/our_rules/add_rule/OurRuleAddViewModel.kt
  app/src/main/java/hous/release/android/presentation/our_rules/edit_rule/OurRuleEditFragment.kt
  app/src/main/java/hous/release/android/presentation/our_rules/edit_rule/OurRuleEditViewModel.kt
  app/src/main/java/hous/release/android/presentation/our_rules/main_rule/OurRulesFragment.kt
  app/src/main/java/hous/release/android/presentation/our_rules/main_rule/OurRulesViewModel.kt
  app/src/main/java/hous/release/android/presentation/our_rules/type/ButtonState.kt
  app/src/main/java/hous/release/android/presentation/our_rules/type/RuleItemViewType.kt
  app/src/main/java/hous/release/android/util/ItemTouchHelperCallback.kt
  app/src/main/java/hous/release/android/util/extension/FragmentExtension.kt
  app/src/main/res/drawable/ic_our_rule_limit.xml
  app/src/main/res/layout/dialog_our_rule_add_error.xml
  app/src/main/res/layout/fragment_our_rule_add.xml
  app/src/main/res/layout/fragment_our_rule_edit.xml
  app/src/main/res/layout/item_our_rules_edit_item.xml
  app/src/main/res/layout/item_our_rules_general_rule.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  data/src/main/java/hous/release/data/datasource/OurRulesDataSource.kt
  data/src/main/java/hous/release/data/entity/request/EditRulesRequest.kt
  data/src/main/java/hous/release/data/entity/response/OurRulesResponse.kt
  data/src/main/java/hous/release/data/repository/OurRulesRepositoryImpl.kt
  data/src/main/java/hous/release/data/service/OurRulesService.kt
  domain/src/main/java/hous/release/domain/entity/ApiResult.kt
  domain/src/main/java/hous/release/domain/entity/RuleType.kt
  domain/src/main/java/hous/release/domain/entity/response/OurRule.kt
  domain/src/main/java/hous/release/domain/repository/OurRulesRepository.kt
  domain/src/main/java/hous/release/domain/usecase/PutEditOurRulesUseCase.kt
Labels: 준원🐻, feat, Pull Request🔥

#87 #85 [ui] 알림 리스트
  app/src/main/AndroidManifest.xml
  app/src/main/java/hous/release/android/presentation/notification/NotificationActivity.kt
  app/src/main/res/drawable/ic_notification_badge.xml
  app/src/main/res/drawable/ic_notification_rules.xml
  app/src/main/res/drawable/ic_notification_to_do.xml
  app/src/main/res/layout/activity_notification.xml
  app/src/main/res/layout/fragment_create_room.xml
  app/src/main/res/layout/fragment_enter_room_code.xml
  app/src/main/res/layout/item_notification.xml
  app/src/main/res/values/strings.xml
Labels: 연주😻, ui, Pull Request🔥

#84 #83 [ui] Profile 메인 뷰 구현
  app/src/main/java/hous/release/android/presentation/profile/ProfileFragment.kt
  app/src/main/java/hous/release/android/presentation/profile/ProfileViewModel.kt
  app/src/main/java/hous/release/android/presentation/profile/adapter/ProfilePersonalityAdapter.kt
  app/src/main/res/drawable/ic_profile_alarm_gray.xml
  app/src/main/res/drawable/ic_profile_alarm_white.xml
  app/src/main/res/drawable/ic_profile_edit.xml
  app/src/main/res/drawable/ic_profile_empty_tendency.xml
  app/src/main/res/drawable/ic_profile_next.xml
  app/src/main/res/drawable/ic_profile_setting_white.xml
  app/src/main/res/drawable/ic_setting_gray.xml
  app/src/main/res/drawable/shape_black_fill_8_rect.xml
  app/src/main/res/drawable/shape_g3_fill_2_rect.xml
  app/src/main/res/drawable/shape_g6_line_20_rect.xml
  app/src/main/res/drawable/shape_white_fill_100_circle.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/item_profile_personality.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  domain/src/main/java/hous/release/domain/entity/PersonalityInfo.kt
  domain/src/main/java/hous/release/domain/entity/ProfileSet.kt
  domain/src/main/java/hous/release/domain/entity/response/Profile.kt
Labels: 영주🐼, ui, Pull Request🔥

#82 #74 [ui/feat] UserInput 데이트피커 구현
  app/src/main/java/hous/release/android/presentation/login/UserInputActivity.kt
  app/src/main/java/hous/release/android/presentation/login/UserInputViewModel.kt
  app/src/main/java/hous/release/android/util/dialog/DatePickerClickListener.kt
  app/src/main/java/hous/release/android/util/dialog/DatePickerDialog.kt
  app/src/main/java/hous/release/android/util/dialog/WarningDialogFragment.kt
  app/src/main/res/layout/activity_user_input.xml
  app/src/main/res/layout/dialog_date_picker.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: 영주🐼, feat, ui, Pull Request🔥

#89 #86 [feat] 알림 리스트 서버 통신 및 무한 스크롤 구현
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  app/build.gradle.kts
  app/src/main/java/hous/release/android/di/RepositoryModule.kt
  app/src/main/java/hous/release/android/di/RetrofitServiceModule.kt
  app/src/main/java/hous/release/android/presentation/notification/NotificationActivity.kt
  app/src/main/java/hous/release/android/presentation/notification/NotificationViewModel.kt
  app/src/main/java/hous/release/android/presentation/notification/paging/NotificationPagingAdapter.kt
  app/src/main/java/hous/release/android/util/binding/BindingAdapters.kt
  app/src/main/res/layout/item_notification.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
  buildSrc/src/main/java/Deps.kt
  data/build.gradle.kts
  data/src/main/java/hous/release/data/datasource/NotificationDataSource.kt
  data/src/main/java/hous/release/data/datasource/NotificationPagingSource.kt
  data/src/main/java/hous/release/data/entity/response/NotificationResponse.kt
  data/src/main/java/hous/release/data/repository/NotificationRepositoryImpl.kt
  data/src/main/java/hous/release/data/service/NotificationService.kt
  domain/build.gradle.kts
  domain/src/main/java/hous/release/domain/entity/NotificationType.kt
  domain/src/main/java/hous/release/domain/entity/response/Notification.kt
  domain/src/main/java/hous/release/domain/repository/NotificationRepository.kt
Labels: 연주😻, feat, Pull Request🔥

#90 #88 [feat] Profile 서버통신 구현
  app/src/main/java/hous/release/android/di/RepositoryModule.kt
  app/src/main/java/hous/release/android/di/RetrofitServiceModule.kt
  app/src/main/java/hous/release/android/presentation/login/LoginViewModel.kt
  app/src/main/java/hous/release/android/presentation/profile/ProfileFragment.kt
  app/src/main/java/hous/release/android/presentation/profile/ProfileViewModel.kt
  app/src/main/res/layout/fragment_profile.xml
  data/src/main/java/hous/release/data/datasource/ProfileDataSource.kt
  data/src/main/java/hous/release/data/entity/TestScoreEntity.kt
  data/src/main/java/hous/release/data/entity/TokenEntity.kt
  data/src/main/java/hous/release/data/entity/response/LoginResponse.kt
  data/src/main/java/hous/release/data/entity/response/ProfileResponse.kt
  data/src/main/java/hous/release/data/entity/response/SignUpResponse.kt
  data/src/main/java/hous/release/data/repository/ProfileRepositoryImpl.kt
  data/src/main/java/hous/release/data/service/ProfileService.kt
  domain/src/main/java/hous/release/domain/entity/TestScore.kt
  domain/src/main/java/hous/release/domain/entity/Token.kt
  domain/src/main/java/hous/release/domain/entity/response/Login.kt
  domain/src/main/java/hous/release/domain/entity/response/Profile.kt
  domain/src/main/java/hous/release/domain/entity/response/SignUp.kt
  domain/src/main/java/hous/release/domain/repository/ProfileRepository.kt
Labels: 영주🐼, feat, Pull Request🔥

#91 #78 [feat/ui] 규칙 삭제 뷰/ 기능/ 서버 통신
  app/src/main/java/hous/release/android/di/DispatcherModule.kt
  app/src/main/java/hous/release/android/di/RepositoryModule.kt
  app/src/main/java/hous/release/android/presentation/our_rules/adapter/OurRulesDeleteAdapter.kt
  app/src/main/java/hous/release/android/presentation/our_rules/add_rule/OurRuleAddFragment.kt
  app/src/main/java/hous/release/android/presentation/our_rules/add_rule/OurRuleAddOutDialogFragment.kt
  app/src/main/java/hous/release/android/presentation/our_rules/delete_rule/OurRuleDeleteFragment.kt
  app/src/main/java/hous/release/android/presentation/our_rules/delete_rule/OurRuleDeleteViewModel.kt
  app/src/main/java/hous/release/android/presentation/our_rules/edit_rule/OurRuleEditFragment.kt
  app/src/main/res/drawable/ic_our_rules_delete_checked.xml
  app/src/main/res/drawable/ic_our_rules_delete_unchecked.xml
  app/src/main/res/drawable/selector_our_rules_delete_check_box.xml
  app/src/main/res/layout/dialog_our_rule_add_out.xml
  app/src/main/res/layout/fragment_our_rule_delete.xml
  app/src/main/res/layout/item_our_rules_delete_item.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/hous/release/data/datasource/OurRulesDataSource.kt
  data/src/main/java/hous/release/data/entity/request/DeleteRulesRequest.kt
  data/src/main/java/hous/release/data/repository/OurRulesRepositoryImpl.kt
  data/src/main/java/hous/release/data/service/OurRulesService.kt
  domain/src/main/java/hous/release/domain/repository/OurRulesRepository.kt
  domain/src/main/java/hous/release/domain/usecase/DeleteOurRulesUseCase.kt
Labels: 준원🐻, feat, ui, Pull Request🔥

#92 #81 [feat] 배지 뷰 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/hous/release/android/di/RepositoryModule.kt
  app/src/main/java/hous/release/android/di/RetrofitServiceModule.kt
  app/src/main/java/hous/release/android/presentation/badge/BadgeActivity.kt
  app/src/main/java/hous/release/android/presentation/badge/BadgeViewModel.kt
  app/src/main/java/hous/release/android/presentation/badge/HousBadgeScreen.kt
  app/src/main/java/hous/release/android/presentation/profile/ProfileFragment.kt
  app/src/main/java/hous/release/android/util/component/HousBadge.kt
  app/src/main/java/hous/release/android/util/component/MemberTap.kt
  app/src/main/java/hous/release/android/util/component/Pentagon.kt
  app/src/main/java/hous/release/android/util/component/ToDoProgressBar.kt
  app/src/main/java/hous/release/android/util/component/TodoMainEmpty.kt
  app/src/main/java/hous/release/android/util/component/dpToSp.kt
  data/src/main/java/hous/release/data/datasource/BadgeDataSource.kt
  data/src/main/java/hous/release/data/entity/BadgeEntity.kt
  data/src/main/java/hous/release/data/entity/response/BadgeResponse.kt
  data/src/main/java/hous/release/data/repository/BadgeRepositoryImpl.kt
  data/src/main/java/hous/release/data/service/BadgeService.kt
  domain/src/main/java/hous/release/domain/entity/response/BadgeContent.kt
  domain/src/main/java/hous/release/domain/repository/BadgeRepository.kt
Labels: 원용🐉, feat, Pull Request🔥

#94 #93 [ui/feat] PersonalityTest UI랑 API 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/hous/release/android/di/RepositoryModule.kt
  app/src/main/java/hous/release/android/di/RetrofitServiceModule.kt
  app/src/main/java/hous/release/android/presentation/badge/HousBadgeScreen.kt
  app/src/main/java/hous/release/android/presentation/personality/result/PersonalityResultActivity.kt
  app/src/main/java/hous/release/android/presentation/personality/result/PersonalityResultViewModel.kt
  app/src/main/java/hous/release/android/presentation/profile/ProfileFragment.kt
  app/src/main/java/hous/release/android/util/binding/BindingAdapters.kt
  app/src/main/res/drawable/ic_back_g4.xml
  app/src/main/res/drawable/ic_back_g5.xml
  app/src/main/res/drawable/ic_personality_result_check_blue.xml
  app/src/main/res/drawable/ic_personality_result_check_green.xml
  app/src/main/res/drawable/ic_personality_result_check_purple.xml
  app/src/main/res/drawable/ic_personality_result_check_red.xml
  app/src/main/res/drawable/ic_personality_result_check_yellow.xml
  app/src/main/res/drawable/shape_white_fill_20_rect.xml
  app/src/main/res/layout/activity_edit_hous_name.xml
  app/src/main/res/layout/activity_notification.xml
  app/src/main/res/layout/activity_personality_result.xml
  app/src/main/res/layout/fragment_create_room.xml
  app/src/main/res/layout/fragment_daily.xml
  app/src/main/res/layout/fragment_enter_room_code.xml
  app/src/main/res/layout/fragment_member.xml
  app/src/main/res/layout/fragment_our_rule.xml
  app/src/main/res/layout/fragment_our_rule_add.xml
  app/src/main/res/layout/fragment_our_rule_delete.xml
  app/src/main/res/layout/fragment_our_rule_edit.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/hous/release/data/datasource/PersonalityDataSource.kt
  data/src/main/java/hous/release/data/entity/response/PersonalityResultResponse.kt
  data/src/main/java/hous/release/data/repository/PersonalityRepositoryImpl.kt
  data/src/main/java/hous/release/data/service/PersonalityService.kt
  domain/src/main/java/hous/release/domain/entity/response/PersonalityResult.kt
  domain/src/main/java/hous/release/domain/repository/PersonalityRepository.kt
Labels: 영주🐼, feat, ui, Pull Request🔥
