Repository Hous-Release/hous-AOS, pull requests merged in 2022-09, with the labels that each got.

#27 #26 [feat] ourRules main 뷰 서버 통신
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/hous/release/android/HousApplication.kt
  app/src/main/java/hous/release/android/di/RepositoryModule.kt
  app/src/main/java/hous/release/android/di/RetrofitModule.kt
  app/src/main/java/hous/release/android/di/RetrofitServiceModule.kt
  app/src/main/java/hous/release/android/presentation/our_rules/OurRulesFragment.kt
  app/src/main/java/hous/release/android/presentation/our_rules/OurRulesViewModel.kt
  app/src/main/java/hous/release/android/presentation/our_rules/adapter/OurRulesAdapter.kt
  app/src/main/java/hous/release/android/presentation/todo/MyToDoAdapter.kt
  app/src/main/java/hous/release/android/presentation/todo/OurToDoAdapter.kt
  app/src/main/java/hous/release/android/util/HousDeBugTree.kt
  app/src/main/res/layout/fragment_our_rule.xml
  app/src/main/res/layout/item_our_rules_general_rule.xml
  app/src/main/res/layout/item_our_rules_representative_rule_bottom.xml
  app/src/main/res/layout/item_our_rules_representative_rule_middle.xml
  app/src/main/res/layout/item_our_rules_representative_rule_top.xml
  data/src/main/java/hous/release/data/datasource/OurRulesDataSource.kt
  data/src/main/java/hous/release/data/entity/OurRulesEntity.kt
  data/src/main/java/hous/release/data/entity/response/OurRulesResponse.kt
  data/src/main/java/hous/release/data/repository/OurRulesRepositoryImpl.kt
  data/src/main/java/hous/release/data/service/OurRulesService.kt
  domain/src/main/java/hous/release/domain/entity/OurRulesContent.kt
  domain/src/main/java/hous/release/domain/entity/Rule.kt
  domain/src/main/java/hous/release/domain/entity/response/OurRule.kt
  domain/src/main/java/hous/release/domain/repository/OurRulesRepository.kt
  gradle.properties
Labels: 준원🐻, feat, Pull Request🔥

#29 #14 [feat] Login뷰 / 카카오로그인 로직 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/hous/release/android/di/RepositoryModule.kt
  app/src/main/java/hous/release/android/di/RetrofitServiceModule.kt
  app/src/main/java/hous/release/android/login/LoginActivity.kt
  app/src/main/java/hous/release/android/presentation/login/LoginActivity.kt
  app/src/main/java/hous/release/android/presentation/login/LoginViewModel.kt
  app/src/main/java/hous/release/android/presentation/login/UserInputActivity.kt
  app/src/main/java/hous/release/android/util/extension/ContextExt.kt
  app/src/main/java/hous/release/android/util/extension/EventExtension.kt
  app/src/main/java/hous/release/android/util/extension/LiveDataExtension.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_user_input.xml
  data/build.gradle.kts
  data/src/main/java/hous/release/data/datasource/AuthDataSource.kt
  data/src/main/java/hous/release/data/entity/TokenEntity.kt
  data/src/main/java/hous/release/data/entity/request/LoginRequest.kt
  data/src/main/java/hous/release/data/entity/response/LoginResponse.kt
  data/src/main/java/hous/release/data/repository/AuthRepositoryImpl.kt
  data/src/main/java/hous/release/data/service/AuthService.kt
  data/src/main/java/hous/release/data/service/KakaoLoginService.kt
  domain/src/main/java/hous/release/domain/entity/Token.kt
  domain/src/main/java/hous/release/domain/entity/response/Login.kt
  domain/src/main/java/hous/release/domain/repository/AuthRepository.kt
Labels: 영주🐼, feat, fix, Pull Request🔥

#33 #32 [feat] 우리집 규칙 추가, 수정, 삭제 뷰로 navigate하는 바텀시트 만들기
  app/src/main/java/hous/release/android/presentation/our_rules/OurRuleAddFragment.kt
  app/src/main/java/hous/release/android/presentation/our_rules/OurRuleDeleteFragment.kt
  app/src/main/java/hous/release/android/presentation/our_rules/OurRuleEditFragment.kt
  app/src/main/java/hous/release/android/presentation/our_rules/OurRulesBottomSheetDialogFragment.kt
  app/src/main/java/hous/release/android/presentation/our_rules/OurRulesFragment.kt
  app/src/main/java/hous/release/android/presentation/our_rules/OurRulesViewModel.kt
  app/src/main/java/hous/release/android/presentation/our_rules/adapter/OurRulesAdapter.kt
  app/src/main/java/hous/release/android/util/ItemDiffCallback.kt
  app/src/main/res/drawable/shape_white_fill_top10_rect.xml
  app/src/main/res/layout/activity_our_rules.xml
  app/src/main/res/layout/dialog_our_rule.xml
  app/src/main/res/layout/fragment_our_rule.xml
  app/src/main/res/layout/fragment_our_rule_add.xml
  app/src/main/res/layout/fragment_our_rule_delete.xml
  app/src/main/res/layout/fragment_our_rule_edit.xml
  app/src/main/res/layout/item_our_rules_general_rule.xml
  app/src/main/res/navigation/nav_our_rules.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
  data/src/main/java/hous/release/data/datasource/OurRulesDataSource.kt
  data/src/main/java/hous/release/data/entity/OurRulesEntity.kt
  data/src/main/java/hous/release/data/entity/response/OurRulesResponse.kt
  data/src/main/java/hous/release/data/repository/OurRulesRepositoryImpl.kt
  domain/src/main/java/hous/release/domain/entity/OurRulesContent.kt
  domain/src/main/java/hous/release/domain/entity/response/OurRule.kt
  domain/src/main/java/hous/release/domain/repository/OurRulesRepository.kt
  domain/src/main/java/hous/release/domain/usecase/OurRulesUseCase.kt
Labels: 준원🐻, feat, Pull Request🔥

#37 #36 [ui] 우리집 규칙 추가 뷰 UI 구현
  app/src/main/java/hous/release/android/presentation/our_rules/OurRuleAddFragment.kt
  app/src/main/java/hous/release/android/presentation/our_rules/OurRulesFragment.kt
  app/src/main/java/hous/release/android/presentation/our_rules/OurRulesNavigateBottomSheetDialogFragment.kt
  app/src/main/java/hous/release/android/presentation/our_rules/add_rule/OurRuleAddErrorDialogFragment.kt
  app/src/main/java/hous/release/android/presentation/our_rules/add_rule/OurRuleAddFragment.kt
  app/src/main/java/hous/release/android/presentation/our_rules/add_rule/OurRuleAddOutDialogFragment.kt
  app/src/main/res/drawable/ic_our_rule_plus_btn.xml
  app/src/main/res/drawable/shape_black_line.xml
  app/src/main/res/layout/dialog_our_rule_add_error.xml
  app/src/main/res/layout/dialog_our_rule_add_out.xml
  app/src/main/res/layout/dialog_our_rule_navigate.xml
  app/src/main/res/layout/fragment_our_rule_add.xml
  app/src/main/res/navigation/nav_our_rules.xml
  app/src/main/res/values/appearance.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 준원🐻, ui, Pull Request🔥

#39 #22 [ui] Hous 화면 레이아웃
  app/src/main/res/drawable/ic_arrow_right.xml
  app/src/main/res/drawable/ic_hous_copy_code.xml
  app/src/main/res/drawable/ic_hous_edit.xml
  app/src/main/res/drawable/ic_hous_my_todo.xml
  app/src/main/res/drawable/ic_profile_blue.xml
  app/src/main/res/drawable/ic_profile_green.xml
  app/src/main/res/drawable/ic_profile_purple.xml
  app/src/main/res/drawable/ic_profile_red.xml
  app/src/main/res/drawable/ic_profile_yellow.xml
  app/src/main/res/drawable/progress_hous.xml
  app/src/main/res/drawable/shape_blue_fill_oval.xml
  app/src/main/res/drawable/shape_blue_l1_fill_oval.xml
  app/src/main/res/drawable/shape_white_fill_bottom_right_8_rect.xml
  app/src/main/res/layout/fragment_enter_room.xml
  app/src/main/res/layout/fragment_hous.xml
  app/src/main/res/layout/item_hous_homies.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: 연주😻, ui, Pull Request🔥
