Repository Hous-Release/hous-AOS, pull requests merged in 2022-12, with the labels that each got.

#155 #154 [feat/fix] 방참여 중 이탈 시 이슈 및 Hous- 탭 QA 수정사항 반영
  app/src/main/java/hous/release/android/di/RetrofitModule.kt
  app/src/main/java/hous/release/android/presentation/enter_room/enter_room_code/EnterRoomCodeFragment.kt
  app/src/main/java/hous/release/android/presentation/enter_room/enter_room_code/EnterRoomCodeViewModel.kt
  app/src/main/java/hous/release/android/presentation/hous/EditHousNameActivity.kt
  app/src/main/java/hous/release/android/presentation/hous/EditHousNameViewModel.kt
  app/src/main/java/hous/release/android/presentation/hous/HousFragment.kt
  app/src/main/java/hous/release/android/presentation/login/LoginActivity.kt
  app/src/main/java/hous/release/android/presentation/login/UserInputActivity.kt
  app/src/main/java/hous/release/android/presentation/main/MainActivity.kt
  app/src/main/java/hous/release/android/presentation/out_room/OutRoomActivity.kt
  app/src/main/java/hous/release/android/presentation/settings/SettingsActivity.kt
  app/src/main/java/hous/release/android/presentation/tutorial/TutorialActivity.kt
  app/src/main/java/hous/release/android/presentation/withdraw/WithdrawActivity.kt
  app/src/main/java/hous/release/android/util/ToastMessageUtil.kt
  app/src/main/res/layout/fragment_enter_room_code.xml
  app/src/main/res/values/strings.xml
Labels: 연주😻, feat, fix

#156 #153 [fix] fix to do update
  app/src/main/java/hous/release/android/presentation/our_rules/add_rule/OurRuleAddErrorDialogFragment.kt
  app/src/main/java/hous/release/android/presentation/todo/add/AddToDoFragment.kt
  app/src/main/java/hous/release/android/presentation/todo/add/AddToDoVIewModel.kt
  app/src/main/java/hous/release/android/presentation/todo/add/AddTodoUserScreen.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/TodoLimitDialog.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/daily/DailyFragment.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/member/MemberFragment.kt
  app/src/main/java/hous/release/android/presentation/todo/edit/EditToDoFragment.kt
  app/src/main/java/hous/release/android/presentation/todo/edit/EditToDoUserScreen.kt
  app/src/main/java/hous/release/android/presentation/todo/edit/EditToDoViewModel.kt
  app/src/main/java/hous/release/android/presentation/todo/viewmodel/UpdateToDoViewModel.kt
  app/src/main/java/hous/release/android/util/component/ToDoButton.kt
  app/src/main/java/hous/release/android/util/component/ToDoUserScreen.kt
  app/src/main/res/layout/fragment_edit_to_do.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/hous/release/data/repository/TodoRepositoryImpl.kt
Labels: 준원🐻, feat, fix, Pull Request🔥

#158 #152 [fix] todo, badge QA 반영
  app/src/main/java/hous/release/android/presentation/todo/detail/TodoDetailActivity.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/TodoDetailViewModel.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/daily/DailyAdapter.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/daily/DailyFragment.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/daily/DailyMyTodoAdapter.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/daily/DailyOurTodoAdapter.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/member/MemberFragment.kt
  app/src/main/java/hous/release/android/presentation/todo/main/TodoFragment.kt
  app/src/main/java/hous/release/android/presentation/todo/main/TodoViewModel.kt
  app/src/main/java/hous/release/android/util/component/HousBadge.kt
  app/src/main/java/hous/release/android/util/component/MemberTap.kt
  app/src/main/res/drawable/ic_todo_limit.xml
  app/src/main/res/layout/dialog_todo_limit.xml
  app/src/main/res/layout/item_to_do_daily_my_rule.xml
  app/src/main/res/layout/item_to_do_daily_our_rule.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/hous/release/data/entity/response/AllMemberTodoResponse.kt
  data/src/main/java/hous/release/data/entity/response/DailyTodoResponse.kt
  data/src/main/java/hous/release/data/repository/TodoRepositoryImpl.kt
  data/src/main/java/hous/release/data/service/TodoService.kt
  data/src/test/java/hous/release/data/ExampleUnitTest.kt
  data/src/test/java/hous/release/data/MemberTodoMapperTest.kt
  domain/src/main/java/hous/release/domain/entity/response/AllMemberTodo.kt
  domain/src/main/java/hous/release/domain/entity/response/DailyTodo.kt
  domain/src/main/java/hous/release/domain/repository/TodoRepository.kt
Labels: 원용🐉, fix, Pull Request🔥

#161 #159 [feat] 방만들기/방참여하기, 우리집 별명 바꾸기, 탈퇴하기 터치 중복 막기
  app/src/main/java/hous/release/android/presentation/enter_room/create_room/CreateRoomFragment.kt
  app/src/main/java/hous/release/android/presentation/enter_room/create_room/CreateRoomViewModel.kt
  app/src/main/java/hous/release/android/presentation/enter_room/enter_room_code/EnterRoomCodeDialogFragment.kt
  app/src/main/java/hous/release/android/presentation/enter_room/enter_room_code/EnterRoomCodeViewModel.kt
  app/src/main/java/hous/release/android/presentation/hous/EditHousNameActivity.kt
  app/src/main/java/hous/release/android/presentation/hous/EditHousNameViewModel.kt
  app/src/main/java/hous/release/android/presentation/withdraw/WithdrawActivity.kt
  app/src/main/java/hous/release/android/presentation/withdraw/WithdrawViewModel.kt
  app/src/main/java/hous/release/android/util/UiEvent.kt
  app/src/main/res/layout/activity_edit_hous_name.xml
  app/src/main/res/values/strings.xml
Labels: 연주😻, feat, Pull Request🔥

#163 #157 [fix] 규칙 수정 QA시트, ToDo 수정 이탈 다이얼로그 로직 수정
  app/src/main/java/hous/release/android/presentation/our_rules/edit_rule/OurRuleEditFragment.kt
  app/src/main/java/hous/release/android/presentation/todo/edit/EditToDoFragment.kt
  app/src/main/java/hous/release/android/presentation/todo/edit/EditToDoViewModel.kt
  app/src/main/res/values/strings.xml
Labels: 준원🐻, fix, Pull Request🔥

#164 #157 [fix] rule 수정 scoller 문제 해결
  app/src/main/java/hous/release/android/presentation/our_rules/edit_rule/OurRuleEditFragment.kt
Labels: 준원🐻, fix

#160 #151 [fix] 프로필, 회원가입 QA 시트
  app/src/main/java/hous/release/android/presentation/login/LoginViewModel.kt
  app/src/main/java/hous/release/android/presentation/login/UserInputActivity.kt
  app/src/main/java/hous/release/android/presentation/login/UserInputViewModel.kt
  app/src/main/java/hous/release/android/presentation/profile/ProfileViewModel.kt
  app/src/main/java/hous/release/android/presentation/profile/edit/ProfileEditActivity.kt
  app/src/main/java/hous/release/android/presentation/profile/edit/ProfileEditViewModel.kt
  app/src/main/java/hous/release/android/util/extension/LiveDataExtension.kt
  app/src/main/res/drawable/selector_profile_edit.xml
  app/src/main/res/layout/activity_homie_profile.xml
  app/src/main/res/layout/activity_profile_edit.xml
  app/src/main/res/layout/activity_user_input.xml
  app/src/main/res/layout/fragment_profile.xml
Labels: 영주🐼, fix, Pull Request🔥

#165 #162 [feat] debug apk 추출 후 슬랙으로 전송 기능 구현
  .github/workflows/Debug_Apk.yml
  .github/workflows/PR_Builder.yml
  app/build.gradle.kts
Labels: 원용🐉, feat, Pull Request🔥

#167 #166 [fix] 2차 QA 적용
  app/src/main/java/hous/release/android/presentation/badge/HousBadgeScreen.kt
  app/src/main/java/hous/release/android/util/component/PersonalityResultImage.kt
  domain/src/main/java/hous/release/domain/entity/TestScore.kt
Labels: 원용🐉, fix, Pull Request🔥

#175 #173 [feat] 강제업데이트 기능
  app/src/main/java/hous/release/android/di/RepositoryModule.kt
  app/src/main/java/hous/release/android/di/RetrofitModule.kt
  app/src/main/java/hous/release/android/di/RetrofitServiceModule.kt
  app/src/main/java/hous/release/android/presentation/force_update/ForceUpdateDialogFragment.kt
  app/src/main/java/hous/release/android/presentation/hous/EditHousNameViewModel.kt
  app/src/main/java/hous/release/android/presentation/network_error/NetworkErrorActivity.kt
  app/src/main/java/hous/release/android/presentation/splash/IntroActivity.kt
  app/src/main/java/hous/release/android/presentation/splash/IntroViewModel.kt
  app/src/main/java/hous/release/android/presentation/withdraw/WithdrawViewModel.kt
  app/src/main/java/hous/release/android/util/extension/ContextExtension.kt
  app/src/main/res/drawable/ic_force_update.xml
  app/src/main/res/layout/activity_intro.xml
  app/src/main/res/layout/dialog_create_room.xml
  app/src/main/res/layout/dialog_force_update.xml
  app/src/main/res/layout/fragment_hous.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/hous/release/data/datasource/VersionDataSource.kt
  data/src/main/java/hous/release/data/entity/response/VersionCheckResponse.kt
  data/src/main/java/hous/release/data/repository/VersionRepositoryImpl.kt
  data/src/main/java/hous/release/data/service/VersionService.kt
  domain/src/main/java/hous/release/domain/entity/response/VersionCheck.kt
  domain/src/main/java/hous/release/domain/repository/VersionRepository.kt
Labels: 연주😻, feat, Pull Request🔥

#174 #171 [feat] log event 버튼 심기
  .github/workflows/Debug_Apk.yml
  app/src/main/java/hous/release/android/HousApplication.kt
  app/src/main/java/hous/release/android/presentation/badge/BadgeActivity.kt
  app/src/main/java/hous/release/android/presentation/hous/HousFragment.kt
  app/src/main/java/hous/release/android/presentation/hous/adapter/HomiesAdapter.kt
  app/src/main/java/hous/release/android/presentation/notification/NotificationActivity.kt
  app/src/main/java/hous/release/android/presentation/our_rules/OurRulesActivity.kt
  app/src/main/java/hous/release/android/presentation/our_rules/main_rule/OurRulesFragment.kt
  app/src/main/java/hous/release/android/presentation/out_room/OutRoomActivity.kt
  app/src/main/java/hous/release/android/presentation/personality/test/PersonalityTestFragment.kt
  app/src/main/java/hous/release/android/presentation/profile/ProfileFragment.kt
  app/src/main/java/hous/release/android/presentation/profile/homie/HomieProfileActivity.kt
  app/src/main/java/hous/release/android/presentation/settings/SettingsActivity.kt
  app/src/main/java/hous/release/android/presentation/splash/IntroActivity.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/TodoDetailActivity.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/daily/DailyFragment.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/member/MemberFragment.kt
  app/src/main/java/hous/release/android/presentation/withdraw/WithdrawActivity.kt
  app/src/main/java/hous/release/android/util/HousLogEvent.kt
Labels: 원용🐉, feat, Pull Request🔥

#181 #180 [fix] 3차 QA 수정
  app/src/main/res/layout/fragment_create_room.xml
  app/src/main/res/layout/fragment_enter_room.xml
  app/src/main/res/layout/fragment_enter_room_code.xml
  app/src/main/res/values/strings.xml
Labels: 연주😻, fix, Pull Request🔥

#179 #178 [fix] rules 수정뷰, rules color
  app/build.gradle.kts
  app/src/main/java/hous/release/android/presentation/our_rules/edit_rule/OurRuleEditViewModel.kt
  app/src/main/res/layout/item_our_rules_general_rule.xml
Labels: 준원🐻, fix, Pull Request🔥

#185 #184 [feat] 오픈소스 라이브러리 링크 이동 추가
  app/src/main/java/hous/release/android/presentation/settings/SettingsActivity.kt
  app/src/main/res/drawable/ic_opensource.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/java/Deps.kt
Labels: 연주😻, feat, Pull Request🔥
