Repository Hous-Release/hous-AOS, pull requests merged in 2023-09, with the labels that each got.

#304 #302 [Feat] MainRule Screen에 대표 룰 UI 적용
  app/src/main/java/hous/release/android/presentation/our_rules/component/main/MainRuleList.kt
  data/src/main/java/hous/release/data/entity/response/rule/MainRulesResponse.kt
  data/src/test/java/hous/release/data/repository/RuleRepositoryImplTest.kt
  data/src/test/java/hous/release/data/service/RuleServiceTest.kt
  data/src/test/res/rule/success_main_rules.json
  designsystem/src/main/java/hous/release/designsystem/component/HousDot.kt
  designsystem/src/main/java/hous/release/designsystem/component/HousRule.kt
  domain/src/main/java/hous/release/domain/entity/rule/MainRule.kt
Labels: 준원🐻, fix, Pull Request🔥

#307 #305 [Refactor] 기존 domain에 있는 Rule -> BaseRule, MainRule -> Rule 로 네이밍 변경
  app/src/main/java/hous/release/android/presentation/our_rules/component/main/MainRuleContent.kt
  app/src/main/java/hous/release/android/presentation/our_rules/component/main/MainRuleList.kt
  app/src/main/java/hous/release/android/presentation/our_rules/screen/MainRuleScreen.kt
  app/src/main/java/hous/release/android/presentation/our_rules/viewmodel/MainRuleViewModel.kt
  data/src/main/java/hous/release/data/datasource/RuleDataSource.kt
  data/src/main/java/hous/release/data/entity/response/rule/RulesResponse.kt
  data/src/main/java/hous/release/data/repository/RuleRepositoryImpl.kt
  data/src/main/java/hous/release/data/service/RuleService.kt
  data/src/test/java/hous/release/data/repository/RuleRepositoryImplTest.kt
  data/src/test/java/hous/release/data/service/RuleServiceTest.kt
  domain/src/main/java/hous/release/domain/entity/BaseRule.kt
  domain/src/main/java/hous/release/domain/entity/rule/DetailRule.kt
  domain/src/main/java/hous/release/domain/entity/rule/OurRulesContent.kt
  domain/src/main/java/hous/release/domain/entity/rule/Rule.kt
  domain/src/main/java/hous/release/domain/entity/todo/TodoWithNew.kt
  domain/src/main/java/hous/release/domain/repository/RuleRepository.kt
  domain/src/main/java/hous/release/domain/usecase/rule/GetMainRulesUseCase.kt
  domain/src/main/java/hous/release/domain/usecase/rule/GetRulesUseCase.kt
  domain/src/main/java/hous/release/domain/usecase/search/SearchRuleUseCase.kt
  domain/src/test/java/hous/release/domain/usecase/SearchRuleUseCaseTest.kt
Labels: 준원🐻, refactor, Pull Request🔥

#309 #306 [feat] 대표 룰 UI
  app/src/main/java/hous/release/android/presentation/our_rules/component/RuleEmptyContent.kt
  app/src/main/java/hous/release/android/presentation/our_rules/component/main/DetailRuleBottomSheetContent.kt
  app/src/main/java/hous/release/android/presentation/our_rules/component/main/MainRuleContent.kt
  app/src/main/java/hous/release/android/presentation/our_rules/component/main/MainRuleList.kt
  app/src/main/java/hous/release/android/presentation/our_rules/component/main/MainRuleToolbar.kt
  app/src/main/java/hous/release/android/presentation/our_rules/component/represent/RepresentRuleList.kt
  app/src/main/java/hous/release/android/presentation/our_rules/component/update/BasicUpdateRuleScreen.kt
  app/src/main/java/hous/release/android/presentation/our_rules/component/update/PhotoGrid.kt
  app/src/main/java/hous/release/android/presentation/our_rules/component/update/RuleAddPhotoButton.kt
  app/src/main/java/hous/release/android/presentation/our_rules/component/update/RulePhotoStatusBar.kt
  app/src/main/java/hous/release/android/presentation/our_rules/graph/RuleNavGraph.kt
  app/src/main/java/hous/release/android/presentation/our_rules/model/DetailRuleUiModel.kt
  app/src/main/java/hous/release/android/presentation/our_rules/model/RepresentRuleUiModel.kt
  app/src/main/java/hous/release/android/presentation/our_rules/screen/AddRuleScreen.kt
  app/src/main/java/hous/release/android/presentation/our_rules/screen/DeleteRuleScreen.kt
  app/src/main/java/hous/release/android/presentation/our_rules/screen/MainRuleScreen.kt
  app/src/main/java/hous/release/android/presentation/our_rules/screen/RepresentRuleScreen.kt
  app/src/main/java/hous/release/android/presentation/our_rules/screen/UpdateRuleScreen.kt
  app/src/main/java/hous/release/android/presentation/our_rules/screen/type/RulesScreens.kt
  app/src/main/res/drawable/ic_our_rules_delete_unchecked.xml
  app/src/main/res/drawable/selector_our_rules_delete_check_box.xml
  app/src/main/res/values/strings.xml
  designsystem/src/main/java/hous/release/designsystem/component/HousCheckBox.kt
  designsystem/src/main/res/drawable/ic_check.xml
Labels: 준원🐻, feat, Pull Request🔥

#310 #308 [feat] 대표 룰 수정 api 및 presentation 로직
  app/src/main/java/hous/release/android/di/ReducerModule.kt
  app/src/main/java/hous/release/android/presentation/our_rules/component/main/MainRuleList.kt
  app/src/main/java/hous/release/android/presentation/our_rules/component/update/PhotoGrid.kt
  app/src/main/java/hous/release/android/presentation/our_rules/event/RepresentRulesReducer.kt
  app/src/main/java/hous/release/android/presentation/our_rules/graph/RuleNavGraph.kt
  app/src/main/java/hous/release/android/presentation/our_rules/screen/RepresentRuleScreen.kt
  app/src/main/java/hous/release/android/presentation/our_rules/viewmodel/RepresentRuleViewModel.kt
  app/src/main/res/values/strings.xml
  data/src/main/java/hous/release/data/datasource/RuleDataSource.kt
  data/src/main/java/hous/release/data/entity/request/rule/UpdateRepresentRulesRequest.kt
  data/src/main/java/hous/release/data/repository/RuleRepositoryImpl.kt
  data/src/main/java/hous/release/data/service/RuleService.kt
  designsystem/src/main/java/hous/release/designsystem/component/HousDot.kt
  domain/src/main/java/hous/release/domain/repository/RuleRepository.kt
  domain/src/main/java/hous/release/domain/usecase/rule/UpdateRepresentRulesUseCase.kt
Labels: 준원🐻, feat, Pull Request🔥

#315 #312 [ui] Hous- Screen - 대표 룰 숫자 -> Dot로 변경
  app/src/main/java/hous/release/android/presentation/hous/HousFragment.kt
  app/src/main/res/layout/fragment_hous.xml
Labels: 준원🐻, ui, Pull Request🔥

#314 #257 [feat] 성향결과 이미지 다운로드 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/hous/release/android/di/RepositoryModule.kt
  app/src/main/java/hous/release/android/presentation/personality/result/PersonalityResultActivity.kt
  app/src/main/java/hous/release/android/presentation/personality/result/PersonalityResultViewModel.kt
  app/src/main/res/drawable/ic_download.xml
  app/src/main/res/layout/activity_personality_result.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/hous/release/data/entity/response/PersonalityResultResponse.kt
  data/src/main/java/hous/release/data/repository/ImageRepositoryImpl.kt
  domain/src/main/java/hous/release/domain/entity/response/PersonalityResult.kt
  domain/src/main/java/hous/release/domain/repository/ImageRepository.kt
Labels: 영주🐼, feat, Pull Request🔥

#316 #313 [fix] Rule dropdown menu Clip radius 값 수정
  app/src/main/java/hous/release/android/presentation/our_rules/component/main/MainRuleDropDownMenu.kt
  app/src/main/res/values/strings.xml
Labels: 준원🐻, fix, Pull Request🔥
