Repository Hous-Release/hous-AOS, pull requests merged in 2023-02, with the labels that each got.

#187 #186 [refact] livedata를 flow로 변경하기
  app/src/main/java/hous/release/android/presentation/login/UserInputActivity.kt
  app/src/main/java/hous/release/android/presentation/login/UserInputViewModel.kt
  app/src/main/java/hous/release/android/presentation/personality/result/PersonalityResultActivity.kt
  app/src/main/java/hous/release/android/presentation/personality/result/PersonalityResultViewModel.kt
  app/src/main/java/hous/release/android/presentation/profile/ProfileFragment.kt
  app/src/main/java/hous/release/android/presentation/profile/ProfileViewModel.kt
  app/src/main/java/hous/release/android/presentation/profile/adapter/ProfilePersonalityAdapter.kt
  app/src/main/java/hous/release/android/presentation/profile/edit/ProfileEntity.kt
  app/src/main/java/hous/release/android/presentation/profile/homie/HomieProfileActivity.kt
  app/src/main/java/hous/release/android/presentation/profile/homie/HomieProfileViewModel.kt
  app/src/main/java/hous/release/android/presentation/tutorial/TutorialActivity.kt
  app/src/main/java/hous/release/android/presentation/tutorial/TutorialViewModel.kt
  app/src/main/java/hous/release/android/presentation/tutorial/adapter/TutorialAdapter.kt
  app/src/main/java/hous/release/android/util/OnSingleClickListener.kt
  app/src/main/java/hous/release/android/util/extension/ContextExtension.kt
  app/src/main/res/layout/activity_homie_profile.xml
  app/src/main/res/layout/activity_personality_result.xml
  app/src/main/res/layout/activity_tutorial.xml
  app/src/main/res/layout/activity_user_input.xml
  app/src/main/res/layout/dialog_date_picker.xml
  app/src/main/res/layout/fragment_profile.xml
  data/src/main/java/hous/release/data/entity/response/PersonalityResultResponse.kt
  domain/src/main/java/hous/release/domain/entity/response/PersonalityResult.kt
  domain/src/main/java/hous/release/domain/entity/response/Profile.kt
Labels: 영주🐼, refactor, Pull Request🔥

#189 #188[fix] 개강 업데이트 전 수정사항 반영
  app/src/main/assets/splash.json
  app/src/main/java/hous/release/android/presentation/personality/test/PersonalityTestViewModel.kt
  app/src/main/res/color/selector_personality_test_text.xml
  app/src/main/res/drawable/ic_test_left.xml
  app/src/main/res/drawable/ic_test_left_click.xml
  app/src/main/res/drawable/ic_test_right.xml
  app/src/main/res/drawable/ic_test_right_click.xml
  app/src/main/res/drawable/selector_personality_test_btn.xml
  app/src/main/res/drawable/shape_blue_edit_fill_8_rect.xml
Labels: 원용🐉, fix, Pull Request🔥

#191 #190 [feat] URI 분리
  .github/workflows/PR_Builder.yml
  app/build.gradle.kts
Labels: 원용🐉, feat, Pull Request🔥

#197 #196 [fix] 튜토리얼 버튼 radius, 우리 집 별명 바꾸기 마진값 수정, 프로필 수정 마진값 수정
  app/src/main/res/drawable/selector_userinput_button.xml
  app/src/main/res/drawable/shape_blue_fill_16_rect.xml
  app/src/main/res/drawable/shape_g4_fill_8_rect.xml
  app/src/main/res/layout/activity_edit_hous_name.xml
  app/src/main/res/layout/activity_profile_edit.xml
  app/src/main/res/layout/activity_tutorial.xml
Labels: 영주🐼, fix, Pull Request🔥

#199 #198 [feat] 중복 Rule Name 생성시 Toast 메세지 띄우기
  app/src/main/java/hous/release/android/presentation/our_rules/add_rule/OurRuleAddFragment.kt
  app/src/main/java/hous/release/android/presentation/our_rules/add_rule/OurRuleAddViewModel.kt
  app/src/main/res/values/strings.xml
  data/src/main/java/hous/release/data/datasource/OurRulesDataSource.kt
  data/src/main/java/hous/release/data/repository/OurRulesRepositoryImpl.kt
  domain/src/main/java/hous/release/domain/repository/OurRulesRepository.kt
  domain/src/main/java/hous/release/domain/usecase/PostAddRulesUseCase.kt
Labels: feat

#201 #200 [add] 프로필에서 오각형 안 보이는 현상 해결
  app/src/main/java/hous/release/android/presentation/profile/ProfileFragment.kt
  app/src/main/java/hous/release/android/presentation/profile/ProfileViewModel.kt
  app/src/main/java/hous/release/android/presentation/profile/homie/HomieProfileActivity.kt
Labels: 영주🐼, add, Pull Request🔥

#202 release 1.0.6
  .github/workflows/PR_Builder.yml
  app/build.gradle.kts
  app/src/main/assets/splash.json
  app/src/main/java/hous/release/android/presentation/hous/HousFragment.kt
  app/src/main/java/hous/release/android/presentation/hous/adapter/HomiesAdapter.kt
  app/src/main/java/hous/release/android/presentation/login/UserInputActivity.kt
  app/src/main/java/hous/release/android/presentation/login/UserInputViewModel.kt
  app/src/main/java/hous/release/android/presentation/our_rules/add_rule/OurRuleAddFragment.kt
  app/src/main/java/hous/release/android/presentation/our_rules/add_rule/OurRuleAddViewModel.kt
  app/src/main/java/hous/release/android/presentation/personality/result/PersonalityResultActivity.kt
  app/src/main/java/hous/release/android/presentation/personality/result/PersonalityResultViewModel.kt
  app/src/main/java/hous/release/android/presentation/personality/test/PersonalityTestViewModel.kt
  app/src/main/java/hous/release/android/presentation/profile/ProfileFragment.kt
  app/src/main/java/hous/release/android/presentation/profile/ProfileViewModel.kt
  app/src/main/java/hous/release/android/presentation/profile/adapter/ProfilePersonalityAdapter.kt
  app/src/main/java/hous/release/android/presentation/profile/edit/ProfileEditActivity.kt
  app/src/main/java/hous/release/android/presentation/profile/edit/ProfileEntity.kt
  app/src/main/java/hous/release/android/presentation/profile/homie/HomieProfileActivity.kt
  app/src/main/java/hous/release/android/presentation/profile/homie/HomieProfileViewModel.kt
  app/src/main/java/hous/release/android/presentation/tutorial/TutorialActivity.kt
  app/src/main/java/hous/release/android/presentation/tutorial/TutorialViewModel.kt
  app/src/main/java/hous/release/android/presentation/tutorial/adapter/TutorialAdapter.kt
  app/src/main/java/hous/release/android/util/HousLogEvent.kt
  app/src/main/java/hous/release/android/util/OnSingleClickListener.kt
  app/src/main/java/hous/release/android/util/dialog/DatePickerDialog.kt
  app/src/main/java/hous/release/android/util/extension/ContextExtension.kt
  app/src/main/res/color/selector_personality_test_text.xml
  app/src/main/res/drawable/ic_back_g6.xml
  app/src/main/res/drawable/ic_test_left.xml
  app/src/main/res/drawable/ic_test_left_click.xml
  app/src/main/res/drawable/ic_test_right.xml
  app/src/main/res/drawable/ic_test_right_click.xml
  app/src/main/res/drawable/selector_personality_test_btn.xml
  app/src/main/res/drawable/selector_userinput_button.xml
  app/src/main/res/drawable/shape_blue_edit_fill_8_rect.xml
  app/src/main/res/drawable/shape_g4_fill_8_rect.xml
  app/src/main/res/layout/activity_edit_hous_name.xml
  app/src/main/res/layout/activity_homie_profile.xml
  app/src/main/res/layout/activity_personality_result.xml
  app/src/main/res/layout/activity_profile_edit.xml
  app/src/main/res/layout/activity_tutorial.xml
  app/src/main/res/layout/activity_user_input.xml
  app/src/main/res/layout/dialog_date_picker.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  buildSrc/src/main/java/Deps.kt
  data/src/main/java/hous/release/data/datasource/OurRulesDataSource.kt
  data/src/main/java/hous/release/data/entity/response/PersonalityResultResponse.kt
  data/src/main/java/hous/release/data/repository/OurRulesRepositoryImpl.kt
  domain/src/main/java/hous/release/domain/entity/response/PersonalityResult.kt
  domain/src/main/java/hous/release/domain/entity/response/Profile.kt
  domain/src/main/java/hous/release/domain/repository/OurRulesRepository.kt
  domain/src/main/java/hous/release/domain/usecase/PostAddRulesUseCase.kt
Labels: Pull Request🔥
