Repository Hous-Release/hous-AOS, pull requests merged in 2023-06, with the labels that each got.

#216 #215 [ui] UI filter bottom sheet
  domain/src/main/java/hous/release/domain/entity/todo/Homy.kt
  domain/src/main/java/hous/release/domain/usecase/todo/GetHomiesUseCase.kt
  feature/todo/.gitignore
  feature/todo/build.gradle.kts
  feature/todo/consumer-rules.pro
  feature/todo/proguard-rules.pro
  feature/todo/src/androidTest/java/hous/release/feature/todo/ExampleInstrumentedTest.kt
  feature/todo/src/main/AndroidManifest.xml
  feature/todo/src/main/java/hous/release/feature/todo/detail/TodoDetailViewModel.kt
  feature/todo/src/main/java/hous/release/feature/todo/detail/component/FilterBottomSheet.kt
  feature/todo/src/main/res/values/strings.xml
  feature/todo/src/test/java/hous/release/feature/todo/ExampleUnitTest.kt
  feature/todo/src/test/java/hous/release/feature/todo/detail/TodoDetailViewModelTest.kt
  settings.gradle.kts
Labels: 원용🐉, feat, ui, Pull Request🔥

#221 #220 [refactor] usecase generic으로 수정
  domain/src/main/java/hous/release/domain/usecase/SearchRuleUseCase.kt
  domain/src/test/java/hous/release/domain/usecase/SearchRuleUseCaseTest.kt
Labels: 원용🐉, refactor, Pull Request🔥

#218 #217 [feat, ui] todo detail 뷰에 들어가는 컴포넌트들 구현
  designsystem/src/main/res/drawable/ic_back.xml
  designsystem/src/main/res/drawable/ic_filter.xml
  domain/src/main/java/hous/release/domain/entity/todo/FilteredTodo.kt
  domain/src/main/java/hous/release/domain/entity/todo/TodoWithNew.kt
  domain/src/main/java/hous/release/domain/usecase/todo/GetFilteredTodoUseCase.kt
  feature/todo/src/main/java/hous/release/feature/todo/detail/TodoDetailViewModel.kt
  feature/todo/src/main/java/hous/release/feature/todo/detail/component/FilterBottomSheet.kt
  feature/todo/src/main/java/hous/release/feature/todo/detail/component/SearchResultText.kt
  feature/todo/src/main/java/hous/release/feature/todo/detail/component/ToDoItem.kt
  feature/todo/src/main/java/hous/release/feature/todo/detail/component/TodoDetailToolbar.kt
  feature/todo/src/main/java/hous/release/feature/todo/detail/component/TodoFilter.kt
  feature/todo/src/main/res/values/strings.xml
  feature/todo/src/test/java/hous/release/feature/todo/detail/TodoDetailViewModelTest.kt
Labels: 원용🐉, feat, ui, Pull Request🔥

#225 #224 [ui] todo detail 바텀시트 구현
  designsystem/src/main/java/hous/release/designsystem/component/HousDetailBottomSheet.kt
  designsystem/src/main/res/values/strings.xml
  feature/todo/src/main/java/hous/release/feature/todo/detail/TodoDetailScreen.kt
  feature/todo/src/main/java/hous/release/feature/todo/detail/component/TodoDetailBottomSheet.kt
Labels: 원용🐉, ui, Pull Request🔥

#227 #226 [feat] 바텀시트 분기 처리 기능 구현
  domain/src/main/java/hous/release/domain/entity/TodoDetail.kt
  feature/todo/src/main/java/hous/release/feature/todo/detail/TodoDetailScreen.kt
  feature/todo/src/main/java/hous/release/feature/todo/detail/TodoDetailViewModel.kt
  feature/todo/src/main/java/hous/release/feature/todo/detail/component/ToDoItem.kt
  feature/todo/src/main/java/hous/release/feature/todo/detail/component/TodoDetailBottomSheet.kt
Labels: 원용🐉, feat, Pull Request🔥

#231 #229 [feat] search usecase 수정
  app/src/main/java/hous/release/android/di/UseCaseModule.kt
  domain/src/main/java/hous/release/domain/usecase/SearchRuleUseCase.kt
  domain/src/main/java/hous/release/domain/usecase/search/SearchRuleUseCase.kt
  domain/src/main/java/hous/release/domain/usecase/search/matcher/RuleNameMatcher.kt
  domain/src/main/java/hous/release/domain/usecase/search/matcher/StringMatcher.kt
  domain/src/main/java/hous/release/domain/usecase/search/strategy/MixedEnKrMatchStrategy.kt
  domain/src/main/java/hous/release/domain/usecase/search/strategy/RuleNameMatchStrategy.kt
  domain/src/main/java/hous/release/domain/usecase/search/strategy/SimpleMatchStrategy.kt
  domain/src/test/java/hous/release/domain/usecase/SearchRuleUseCaseTest.kt
  domain/src/test/java/hous/release/domain/usecase/search/matcher/RuleNameMatcherTest.kt
  domain/src/test/java/hous/release/domain/usecase/search/strategy/MixedEnKrMatchStrategyTest.kt
  domain/src/test/java/hous/release/domain/usecase/search/strategy/SimpleMatchStrategyTest.kt
  feature/todo/src/main/java/hous/release/feature/todo/detail/TodoDetailViewModel.kt
  feature/todo/src/test/java/hous/release/feature/todo/detail/TodoDetailViewModelTest.kt
Labels: 준원🐻, feat, Pull Request🔥

#239 #238 [delete] 불필요한 파일 삭제
  app/src/main/java/hous/release/android/presentation/todo/detail/TodoBottomSheet.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/TodoDetailActivity.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/TodoDetailViewModel.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/TodoParticipantAdapter.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/daily/DailyAdapter.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/daily/DailyFragment.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/daily/DailyMyTodoAdapter.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/daily/DailyOurTodoAdapter.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/member/MemberAdapter.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/member/MemberFragment.kt
  app/src/main/java/hous/release/android/presentation/todo/detail/member/MemberTodoAdapter.kt
  app/src/main/java/hous/release/android/util/component/DailyTap.kt
  app/src/main/java/hous/release/android/util/component/MemberTap.kt
  app/src/main/res/drawable/ic_daily_change_view.xml
  app/src/main/res/drawable/ic_daily_tab_indicator.xml
  app/src/main/res/layout/activity_todo_detail.xml
  app/src/main/res/layout/fragment_daily.xml
  app/src/main/res/layout/fragment_member.xml
  app/src/main/res/layout/item_to_do_daily.xml
  app/src/main/res/layout/item_to_do_daily_my_rule.xml
  app/src/main/res/layout/item_to_do_daily_our_rule.xml
  app/src/main/res/layout/item_to_do_member.xml
  app/src/main/res/layout/item_to_do_member_day_of_week.xml
  data/src/main/java/hous/release/data/datasource/TodoDataSource.kt
  data/src/main/java/hous/release/data/entity/response/AllMemberTodoResponse.kt
  data/src/main/java/hous/release/data/entity/response/DailyTodoResponse.kt
  data/src/main/java/hous/release/data/entity/response/MemberTodoResponse.kt
  data/src/main/java/hous/release/data/repository/TodoRepositoryImpl.kt
  data/src/main/java/hous/release/data/service/TodoService.kt
  data/src/test/java/hous/release/data/MemberTodoMapperTest.kt
  domain/src/main/java/hous/release/domain/entity/MemberTodo.kt
  domain/src/main/java/hous/release/domain/entity/response/AllMemberTodo.kt
  domain/src/main/java/hous/release/domain/entity/response/DailyTodo.kt
  domain/src/main/java/hous/release/domain/entity/response/MemberTodoContent.kt
  domain/src/main/java/hous/release/domain/repository/TodoRepository.kt
  domain/src/main/java/hous/release/domain/usecase/GetDailyTodosUseCase.kt
  domain/src/main/java/hous/release/domain/usecase/GetMemberTodosUseCase.kt
Labels: 원용🐉, delete, Pull Request🔥

#232 #230 [ui, feat] compose dialog 생성
  designsystem/src/main/java/hous/release/designsystem/component/HousDetailBottomSheet.kt
  designsystem/src/main/java/hous/release/designsystem/component/HousDialog.kt
  feature/todo/src/main/java/hous/release/feature/todo/detail/TodoDetailScreen.kt
  feature/todo/src/main/java/hous/release/feature/todo/detail/TodoDetailViewModel.kt
  feature/todo/src/main/java/hous/release/feature/todo/detail/component/TodoDetailBottomSheet.kt
  feature/todo/src/main/res/values/strings.xml
Labels: 원용🐉, feat, ui, Pull Request🔥

#234 #233 [fix] add edit view & viewmodel 수정
  app/build.gradle.kts
  app/src/main/java/hous/release/android/presentation/todo/add/AddToDoFragment.kt
  app/src/main/java/hous/release/android/presentation/todo/add/AddToDoVIewModel.kt
  app/src/main/java/hous/release/android/presentation/todo/add/AddTodoUserScreen.kt
  app/src/main/java/hous/release/android/presentation/todo/edit/EditToDoFragment.kt
  app/src/main/java/hous/release/android/presentation/todo/edit/EditToDoUserScreen.kt
  app/src/main/java/hous/release/android/presentation/todo/edit/EditToDoViewModel.kt
  app/src/main/java/hous/release/android/presentation/todo/viewmodel/UpdateToDoViewModel.kt
  app/src/main/java/hous/release/android/util/component/ToDoButton.kt
  app/src/main/java/hous/release/android/util/component/ToDoUserScreen.kt
  app/src/main/res/drawable/ic_check_off.xml
  app/src/main/res/drawable/ic_check_on.xml
  app/src/main/res/layout/fragment_add_to_do.xml
  app/src/main/res/layout/fragment_edit_to_do.xml
  app/src/main/res/values/strings.xml
Labels: 원용🐉, fix, Pull Request🔥

#237 #235 [feat] add todo edit todo 화면 이동 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/hous/release/android/di/NavigationModule.kt
  app/src/main/java/hous/release/android/navigation/TodoNavigatorImpl.kt
  app/src/main/java/hous/release/android/presentation/todo/add/AddToDoActivity.kt
  app/src/main/java/hous/release/android/presentation/todo/add/AddTodoUserScreen.kt
  app/src/main/java/hous/release/android/presentation/todo/edit/EditToDoActivity.kt
  app/src/main/java/hous/release/android/presentation/todo/edit/EditToDoUserScreen.kt
  app/src/main/java/hous/release/android/util/component/ToDoUserScreen.kt
  app/src/main/res/layout/fragment_add_to_do.xml
  app/src/main/res/layout/fragment_edit_to_do.xml
  app/src/main/res/navigation/nav_todo_detail.xml
  feature/todo/src/main/java/hous/release/feature/todo/detail/TodoDetailActivity.kt
  feature/todo/src/main/java/hous/release/feature/todo/detail/TodoDetailScreen.kt
  feature/todo/src/main/java/hous/release/feature/todo/detail/navigation/TodoNavigator.kt
Labels: 원용🐉, feat, Pull Request🔥

#243 #240 todo 통신 작업
  data/src/main/java/hous/release/data/datasource/TodoDataSource.kt
  data/src/main/java/hous/release/data/entity/request/todo/FilteredTodoRequest.kt
  data/src/main/java/hous/release/data/entity/response/todo/FilteredTodoResponse.kt
  data/src/main/java/hous/release/data/entity/response/todo/IsAddableTodoResponse.kt
  data/src/main/java/hous/release/data/entity/response/todo/TodoWithNewResponse.kt
  data/src/main/java/hous/release/data/repository/TodoRepositoryImpl.kt
  data/src/main/java/hous/release/data/service/TodoService.kt
  data/src/test/java/hous/release/data/entity/request/todo/FilteredTodoRequestTest.kt
  domain/src/main/java/hous/release/domain/repository/TodoRepository.kt
  domain/src/main/java/hous/release/domain/usecase/todo/GetFilteredTodoUseCase.kt
  domain/src/main/java/hous/release/domain/usecase/todo/GetIsAddableTodoUseCase.kt
  feature/todo/src/main/java/hous/release/feature/todo/detail/TodoDetailViewModel.kt
  feature/todo/src/test/java/hous/release/feature/todo/detail/TodoDetailViewModelTest.kt
Labels: 원용🐉, feat, Pull Request🔥

#245 #242 [feat] todo 끝
  app/src/main/java/hous/release/android/presentation/todo/add/AddToDoVIewModel.kt
  app/src/main/java/hous/release/android/presentation/todo/add/AddTodoUserScreen.kt
  app/src/main/java/hous/release/android/presentation/todo/edit/EditToDoActivity.kt
  app/src/main/java/hous/release/android/presentation/todo/edit/EditToDoUserScreen.kt
  app/src/main/java/hous/release/android/presentation/todo/main/TodoFragment.kt
  app/src/main/java/hous/release/android/presentation/todo/main/TodoViewModel.kt
  app/src/main/java/hous/release/android/util/component/ToDoUserScreen.kt
  app/src/main/res/layout/fragment_to_do.xml
  data/src/main/java/hous/release/data/datasource/TodoDataSource.kt
  data/src/main/java/hous/release/data/entity/request/todo/FilteredTodoRequest.kt
  data/src/main/java/hous/release/data/entity/response/TodoDetailResponse.kt
  data/src/main/java/hous/release/data/repository/TodoRepositoryImpl.kt
  data/src/main/java/hous/release/data/service/TodoService.kt
  data/src/test/java/hous/release/data/entity/request/todo/FilteredTodoRequestTest.kt
  designsystem/src/main/java/hous/release/designsystem/component/HousLimitDialog.kt
  designsystem/src/main/res/drawable/ic_todo_limit.xml
  designsystem/src/main/res/values/strings.xml
  domain/src/main/java/hous/release/domain/usecase/todo/GetToDoUsersUseCase.kt
  domain/src/main/java/hous/release/domain/usecase/todo/GetTodoDetailUseCase.kt
  feature/todo/src/main/java/hous/release/feature/todo/detail/TodoDetailActivity.kt
  feature/todo/src/main/java/hous/release/feature/todo/detail/TodoDetailScreen.kt
  feature/todo/src/main/java/hous/release/feature/todo/detail/TodoDetailViewModel.kt
  feature/todo/src/main/res/values/strings.xml
  feature/todo/src/test/java/hous/release/feature/todo/detail/TodoDetailViewModelTest.kt
  testing/src/main/java/hous/release/testing/PrivateFunctionReflection.kt
Labels: 원용🐉, feat, Pull Request🔥

#246 #244 [Chore] SDK 33으로 버전업
  .gitignore
  app/build.gradle.kts
  app/src/main/java/hous/release/android/presentation/enter_room/EnterRoomFragment.kt
  app/src/main/java/hous/release/android/presentation/force_update/ForceUpdateDialogFragment.kt
  app/src/main/java/hous/release/android/presentation/personality/test/PersonalityTestFragment.kt
  app/src/main/java/hous/release/android/presentation/profile/edit/ProfileEditActivity.kt
  app/src/main/java/hous/release/android/presentation/splash/IntroActivity.kt
  app/src/main/java/hous/release/android/util/BuildUtils.kt
  app/src/main/java/hous/release/android/util/dialog/DatePickerDialog.kt
  app/src/main/java/hous/release/android/util/dialog/WarningDialogFragment.kt
  app/src/main/java/hous/release/android/util/extension/BundleExtensions.kt
  app/src/main/java/hous/release/android/util/extension/IntentExtensions.kt
  buildSrc/src/main/java/Deps.kt
  feature/todo/build.gradle.kts
Labels: 준원🐻, chore, Pull Request🔥

#248 #219 [ui] 회원정보입력 뷰 ui 변경사항 반영
  app/src/main/java/hous/release/android/presentation/login/UserInputActivity.kt
  app/src/main/res/drawable/ic_userinput_checked.xml
  app/src/main/res/drawable/ic_userinput_unchecked.xml
  app/src/main/res/drawable/selector_userinput_button.xml
  app/src/main/res/drawable/selector_userinput_pressed.xml
  app/src/main/res/layout/activity_user_input.xml
  app/src/main/res/layout/dialog_date_picker.xml
  app/src/main/res/values/strings.xml
Labels: 영주🐼, ui, Pull Request🔥

#255 #254 [ui] 세팅뷰 디자인 수정 반영
  app/src/main/res/drawable/ic_alarm.xml
  app/src/main/res/drawable/ic_feedback.xml
  app/src/main/res/drawable/ic_info.xml
  app/src/main/res/drawable/ic_opensource.xml
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/values/strings.xml
Labels: 영주🐼, ui, Pull Request🔥

#253 #252 [ui] 우리집별명수정뷰 디자인 수정 반영
  app/src/main/AndroidManifest.xml
  app/src/main/java/hous/release/android/presentation/hous/EditHousNameActivity.kt
  app/src/main/res/layout/activity_edit_hous_name.xml
  app/src/main/res/values/strings.xml
Labels: 영주🐼, ui, Pull Request🔥

#251 #250 [ui] 방만들기/방참여하기 ui 변경사항 반영
  app/src/main/res/layout/activity_user_input.xml
  app/src/main/res/layout/fragment_create_room.xml
  app/src/main/res/layout/fragment_enter_room_code.xml
  app/src/main/res/values/strings.xml
Labels: 영주🐼, ui, Pull Request🔥
